### PR TITLE
fix a typo in README

### PR DESCRIPTION
**Pull request by andaugust**
found a small typo in the README

### CODE REVIEW

**Review by chibenwa — CHANGES_REQUESTED** [review]
It do not looks like a usefull contribution but thanks anyway ;-)

**Review by chibenwa — CHANGES_REQUESTED** [review]
It do not looks like a usefull contribution but thanks anyway ;-)

**Comment by mbaechler** [comment]
That's hacktoberfest hitting us?

**Comment by mbaechler** [comment]
Please avoid useless PRs, thanks

**Pull request closed without merging**
