### PR TITLE
JAMES-3761 Adds configurable bucketname to MimeMessageStore

### PR DESCRIPTION
**Pull request by mbaechler**
Co-Authored-By: Matthieu Baechler <matthieu@apache.org>

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]
No objections. As it stands it seems to benefit custom code only?

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
```
22:14:18,258 [INFO] There are 2 errors reported by Checkstyle 8.29 with checkstyle.xml ruleset.

22:14:18,263 [ERROR] src/main/java/org/apache/james/blob/api/Store.java:[89] (whitespace) EmptyLineSeparator: 'METHOD_DEF' should be separated from previous statement.

22:14:18,264 [ERROR] src/main/java/org/apache/james/blob/api/Store.java:[96] (whitespace) EmptyLineSeparator: 'METHOD_DEF' should be separated from previous statement.
```

**Comment by jeantil** [comment]
> No objections. As it stands it seems to benefit custom code only?

It is used in the BlobStore backed MailRepository of #987 but we felt that the change made sense on its own as there can be multiple MimeMessageStores in a single assembly even before the BlobStore backed Mailrepository. 
For example pulsar-cassandra-smtp-relay uses both CassandraMailRepository and the pulsar mailqueue both of which use a MimeMessageStore. As it stands neither adds custom qualifiers while wiring the message store. Unless I am mistaken this means that they will both store their respective blobs in the same bucket. While there are not direct consequences this is doesn't seem to be a very desirable situation.

**Comment by chibenwa** [comment]
```
07:25:20,278 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (check-style) on project james-server-mail-store: You have 1 Checkstyle violation. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (check-style) on project james-server-mail-store: You have 1 Checkstyle violation.
```

Still....

**Comment by jeantil** [comment]
I can't thank checkstyle enough for this unhelpful message that nicely omits the place where the violation occurs, my workday is starting I will continuer searching what's wrong later

**Comment by mbaechler** [comment]
test this please

**Pull request merged**
