### PR TITLE
JAMES-3959 Starting distributed James without OpenSearch

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by Arsnael — COMMENTED** [review]
Looks good, but I think we need documentation for it as well, and a little note in upgrade instructions? :)

**Comment by chibenwa** [comment]
> and a little note in upgrade instructions

Not needed: it is not a breaking change...

> we need documentation for it as well

That's the case for the all `search.properties` file as well then...

**Comment by Arsnael** [comment]
> That's the case for the all `search.properties` file as well then...

Well people should know from somewhere that this is possible to do :)

**Comment by quantranhong1999** [comment]
Maybe add a doc at `server/apps/distributed-app/docs/modules/ROOT/pages/configure/search.adoc` note this?

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
