### PR TITLE
Upgrade elasticsearch libraries.

### PR DESCRIPTION
**Pull request by lmilev**
2.2.1 is rolling upgrade compatible with 2.4.6 
External Resources: 
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/setup-upgrade.html

### CODE REVIEW

**Comment by rouazana** [comment]
Thank you, I'm testing the build with your commit here: https://github.com/linagora/james-project/pull/1276

**Comment by chibenwa** [comment]
Hi, we get some test failures on top of this pull request.

Here are the details:

```
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 99.72 sec - in org.apache.james.jmap.cassandra.CassandraVacationIntegrationTest
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] 
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] Results :
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] 
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] Failed tests: 
[9a6c7d5c071585d462e4f0c50c09aff451be63eb]   GetMailboxesMethodTest.getMailboxesShouldErrorInvalidArgumentsWhenRequestIsInvalid:344 1 expectation failed.
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] JSON path [0][1].description doesn't match.
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] Expected: Can not deserialize instance of java.util.ArrayList out of VALUE_TRUE token\n at [Source: {\"ids\":true}; line: 1, column: 2] (through reference chain: org.apache.james.jmap.model.Builder[\"ids\"])
[9a6c7d5c071585d462e4f0c50c09aff451be63eb]   Actual: Can not deserialize instance of java.util.ArrayList out of VALUE_TRUE token
[9a6c7d5c071585d462e4f0c50c09aff451be63eb]  at [Source: {"ids":true}; line: 1, column: 8] (through reference chain: org.apache.james.jmap.model.Builder["ids"])
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] 
[9a6c7d5c071585d462e4f0c50c09aff451be63eb]   SetMessagesMethodTest.setMessagesShouldRejectUpdateWhenPropertyHasWrongType:875 1 expectation failed.
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] JSON path [0][1].notUpdated["581e09b0-063f-11e8-b74e-2317723c663c"].description doesn't match.
[9a6c7d5c071585d462e4f0c50c09aff451be63eb] Expected: isUnread: Can not construct instance of java.lang.Boolean from String value '123': only \"true\" or \"false\" recognized\n at [Source: {\"isUnread\":\"123\"}; line: 1, column: 2] (through reference chain: org.apache.james.jmap.model.Builder[\"isUnread\"])
[9a6c7d5c071585d462e4f0c50c09aff451be63eb]   Actual: isUnread: Can not construct instance of java.lang.Boolean from String value '123': only "true" or "false" recognized
[9a6c7d5c071585d462e4f0c50c09aff451be63eb]  at [Source: {"isUnread":"123"}; line: 1, column: 13] (through reference chain: org.apache.james.jmap.model.Builder["isUnread"])
```

Full build can be seen here https://james.open-paas.org/job/workflow/113/console

It looks like this upgrade subtally impact the version of jackson used, and thus impact the JMAP error massage printing...

**Comment by lmilev** [comment]
Thank you for getting the failure info.

**Comment by chiominto78** [comment]
I AM not a failure I AM a success

**Comment by ieugen** [comment]
Thank you for your contribution @lmilev  .
Sorry for not merging it sooner.
I'm looking to do a Marie Kondo on the PR's and clean them up.

I'll close this issue since the PR is not relevant.
Please reopen if you think otherwise.

**Pull request closed without merging**
