### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by aduprat**
This is just a test.

### CODE REVIEW

**Comment by aduprat** [comment]
Hi from Jenkins

**Comment by ieugen** [comment]
@aduprat I've done automatic builds with Apache Infra https://issues.apache.org/jira/browse/JAMES-3225?filter=-3 . 
Let me know if you need help.

https://builds.apache.org/job/ApacheJames/

**Comment by aduprat** [comment]
Hi Eugen,

I've checked that Jenkins is able to publish feedback on a PR by using the `Github Pull Request Builder` plugin.
I've seen that this plugin is available on the Apache infra.

To go ahead, I need some rights on https://builds.apache.org/job/ApacheJames/

I will be able to give some time for this project next week.

**Comment by ieugen** [comment]
If you are a commmitter, you have all the rights. 
The build is confiugred via the Jenkinsfile.
Very few things are available here https://builds.apache.org/job/ApacheJames/configure .
You don't need to configure anything.
I've added asf-ci as reviewer and if you check the bottom of https://github.com/apache/james-project/pull/217  you will see it's waiting for status.

Captură de ecran de la 2020-07-03 13-08-00
Captură de ecran de la 2020-07-03 13-08-15

**Pull request closed without merging**
