### PR TITLE
Mailbox 315 : port two patches from https://github.com/linagora/james-project/pull/1081

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by chibenwa** [comment]
**clearAllTables** is yet still use. Given that our test strategy relies on creating new keyspace, we might try to remove it fully...

 - It is called in CassandraMapperProvider and I suspect can be safely removed.
 - The Predestroy seems like the mark of previous use in injection, and a quick inspection confirms there is no more such uses.

Can you check?

**Comment by chibenwa** [comment]
We might also want to close the session in an async manner in **CassandraCluster::close** right?

**Comment by chibenwa** [comment]
In CassandraMapperProvider we may want to call close instead.

**Comment by mbaechler** [comment]
I would first merge this one then do what you suggest. The more you put in it, the later you merge.
It's the wrong target repository anyway, we have to close this one and create a new one on linagora.

**Comment by chibenwa** [comment]
I opened https://github.com/linagora/james-project/pull/1273, please close this pull request.

**Pull request closed without merging**
