### PR TITLE
[ENHANCEMENT] Move Sent mailbox up the sort order

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]
Why not but how is that really an enhancement?

**Comment by quantranhong1999** [comment]
> Why not but how is that really an enhancement?

https://github.com/linagora/tmail-flutter/issues/2328

**Comment by Arsnael** [comment]
Not sure an arbitrary decision regarding TMail sorting mailbox options should influence Apache James like that though

**Review by Arsnael — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by chibenwa** [comment]
Can someone take care of the follow up PR onto TMail?

**Comment by quantranhong1999** [comment]
> Can someone take care of the follow up PR onto TMail?

Let me.

**Pull request merged**
