### PR TITLE
Limit the heap size of Cassandra and ES docker containers for tests

### PR DESCRIPTION
**Pull request by Arsnael**
Well as I'm getting tired of having the RAM of my laptop burning to the ground half of the time I run integration tests on James, I decided to take a closer look.

Cassandra by default is deployed with 4Go RAM of heap. ES is deployed with 1Go (well I observed those when running locally)

Now the interesting thing is that some work has been done a while ago to limit the size of Cassandra to 650M for the tests, but the env variable setup was wrong. Thus we were still living with a 4Go memory eater Cassandra. 

I fixed that, and while I was at it, I'm taking a shot at ES too (half, from 1Go to 512M). The rational being, if it passes with Cassandra limited like this, might be as well with ES.

I would like to have a good bunch of CI runs though first to be sure it does not bring instability to the build. If it does, I will change those values and go up gradually until we got a stable build.

If any feedback on this or proposition, don't hesitate :)

### CODE REVIEW

**Review by vttranlina — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]

**Comment by Arsnael** [comment]
First build: green :)

**Comment by Arsnael** [comment]
Tsss not sure related
```
09:54:58,815 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project james-server-webadmin-data: There was a timeout or other error in the fork -> [Help 1]
```

**Comment by Arsnael** [comment]
One green and one red:

```
16:18:00,883 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project james-server-webadmin-mailbox: There was a timeout or other error in the fork -> [Help 1]
```

Not related either...

**Comment by Arsnael** [comment]
```
06:29:22,974 [ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 166.506 s <<< FAILURE! - in org.apache.james.webadmin.integration.rabbitmq.vault.RabbitMQDeletedMessageVaultIntegrationTest
06:29:22,976 [ERROR] vaultEndpointShouldRestoreImapDeletedMailbox{GuiceJamesServer}  Time elapsed: 128.653 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a lambda expression in org.apache.james.webadmin.integration.vault.DeletedMessageVaultIntegrationTest 
Expected size: 1 but was: 0 in:
[] within 2 minutes.
Caused by: java.lang.AssertionError: 

Expected size: 1 but was: 0 in:
[]
```
Hmmm... Not sure what to think of this one. Well I'm gonna raise up a bit to be sure

**Comment by Arsnael** [comment]
2 greens builds :) Ok I squash the fixups and if I get an other green I merge

**Pull request merged**
