### PR TITLE
JAMES-1489 Failing test for UTF-8 IMAP search

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by Arsnael — COMMENTED** [review]
Are you gonna try to solve the issue in this PR or it's just to show we have a problem?

**Comment by chibenwa** [comment]
So far I did not succeeded to solve it, showing that we have a problem is better than nothing.

**Review by Arsnael — APPROVED** [review]

**Review by LanKhuat — APPROVED** [review]

**Comment by jeantil** [comment]
Hi, 

While I think having a failing test to demonstrate that there is an issue is good, I am surprised it has not been tagged unstable. It feel like I missed something ... As it is wouldn't this PR make master's build fail in a systematic manner ?

**Comment by jeantil** [comment]
@Arsnael thanks for clarifying, I had seen the @disabled test but since the PR also added `searchingASingleUTF8CriterionShouldComplete`  which is not disabled I was confused.

**Comment by chibenwa** [comment]
> @Arsnael thanks for clarifying, I had seen the @disabled test but since the PR also added searchingASingleUTF8CriterionShouldComplete which is not disabled I was confused.

@jeantil I did not just took a failing test on the JIRA that I disabled.

I tried to understand the root cause.

I first thought it was a charset handling, the second test proves it is not the case.

I then tought it was a charset cary over issue within the search command parser.

But the real root cause is that our Netty stack is not able to handle a command with several literals and here it gets really complicated with a buggy framing. Ouch. I did not win this battle yet.

Contributing a disabled test allows other contributors to have a look. (That was the approach we followed for the MimeMessage COW?)

**Comment by chibenwa** [comment]
I squashed the fixups. 

:green_apple: build

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
My renewed take on this issue: https://github.com/apache/james-project/pull/980

**Pull request merged**
