### PR TITLE
JAMES-3537 (Email/set create should allow to attach mails) to 3.6.x branch

### PR DESCRIPTION
**Pull request by aasaru**
I'm trying to start the process of identifiying bugfixes merged into master branch and creating PR-s with the same content to 3.6.x branch. My goal is to make 3.6.x branch a stable branch that is long lived and an alternative to building on top of latest branch (that could be unstable at times). Eventually we could make releases like 3.6.1 etch from this branch (though it is a time consuming process so this is why it would be done rather rarely).

So as first candidate I picked this Pull request: https://github.com/apache/james-project/pull/362 and now I'm proposing to merge it to 3.6.x branch.

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Comment by chibenwa** [comment]
There are likely other fixes we might want. 

https://github.com/apache/james-project/pull/374 -> Should absolutly have it IMO

https://github.com/apache/james-project/pull/379 -> Nice to have

**Comment by aasaru** [comment]
@chibenwa thaks for quick response.
I now created PR-s for the ones you mentioned.
I also created a Jira task for myself to keep track of decisions which PR-s to bring over to 3.6.x and which not. The task is: https://issues.apache.org/jira/browse/JAMES-3564
I plan to review the PR-s merged to master every now and then, pick the ones I think are fixes and create new PR-s towards 3.6.x

**Review by Arsnael — APPROVED** [review]

**Comment by aasaru** [comment]
I saw my other two similar PR-s were merged (#383 and #384)
Could this be also merged? Thanks!

**Comment by chibenwa** [comment]
Yes, I was just waiting the :green_apple:  build

**Comment by aasaru** [comment]
yeah, it got delayed for quite a bit. Thanks for merging!

**Pull request merged**
