### PR TITLE
JAMES-3302 More content for Distributed Server documentation

### PR DESCRIPTION
**Pull request by chibenwa**
- Run & Run with docker section fully migrated

 - CLI fully migrated

 - WebAdmin documentation for distributed server, mostly some hyperlink fixes

 - I plan adding information about software components and the way they are implemented in the Architecture page.

The content is taken from the old website, then adapted to distributed server (remove mentions only for XXX server)

The next move will include:

 - Metrics
 - Operator guide
 - Architecture
 - And configuration files explanation skeleton

### CODE REVIEW

**Comment by dleangen** [comment]
Very nice! Thank you so much for joining efforts on the documentation.

I don't yet have a good enough understanding to comment on this part, so I will address this (much) later. In the meantime, keep it coming!

**Comment by chibenwa** [comment]
> Very nice! Thank you so much for joining efforts on the documentation.

Thanks! That's a really nice initiative you started, thanks for creating this nice opportunity.

My first contact with Antora had been really good.

> I don't yet have a good enough understanding to comment on this part, so I will address this (much) later. In the meantime, keep it coming!

Sure, and it would be much welcomed. Especially on the global organization of the documentation.

Actually maybe doing the same job on the advanced server would allow you to be able to provide feedback sooner?

**Comment by dleangen** [comment]
> Actually maybe doing the same job on the advanced server would allow you to be able to provide feedback sooner?

Funny that you mention this. That is exactly what I started doing from this morning! I still need to actually accomplish my personal objective (which has been quite delayed), i.e. to build my own extensible server.

So I will likely be sending another volley of questions on the list regarding the extendable server. As you point out, this should hopefully allow me to understand even more about James, and help with the documentation as well.

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
