### PR TITLE
JAMES-3539 PushSubscription/set create

### PR DESCRIPTION
**Pull request by chibenwa**
Follow up https://github.com/apache/james-project/pull/717

### CODE REVIEW

**Comment by chibenwa** [comment]
```
<p><span style="font-weight:bold">org.apache.james.CassandraLdapJamesServerTest.connectLMTPServerShouldSendShabangOnConnect{GuiceJamesServer}</span></p><div style="text-align:right;">Failing for the past 1 build
          (Since <a href="https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-722/2/" class="model-link"><span style="width: 16px; height: 16px; " class="build-status-icon__wrapper icon-red icon-sm"><span class="build-status-icon__outer"><svg viewBox="0 0 24 24" focusable="false" class="svg-icon "><use href="https://ci-builds.apache.org/images/build-status/build-status-sprite.svg#build-status-static"></use></svg></span><svg viewBox="0 0 24 24" focusable="false" class="svg-icon icon-red icon-sm"><use href="https://ci-builds.apache.org/static/b0bcd58c/images/build-status/build-status-sprite.svg#last-failed"></use></svg></span>#2</a> )
        </div><div style="text-align:right;"><a href="https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-722/2/testReport/junit/org.apache.james/CassandraLdapJamesServerTest/connectLMTPServerShouldSendShabangOnConnect_GuiceJamesServer_/history">Took 0.28 sec.</a></div><div id="description"><div></div></div>
<h3>Error Message</h3><pre>Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for PushSubscriptionRepository was bound.

Requested by:
1  : PushSubscriptionSetCreatePerformer.&lt;init&gt;(PushSubscriptionSetCreatePerformer.scala:50)
      \_ for 1st parameter pushSubscriptionRepository
     at PushSubscriptionSetMethod.&lt;init&gt;(PushSubscriptionSetMethod.scala:36)
      \_ for 1st parameter createPerformer
     at RFC8621MethodsModule.configure(RFC8621MethodsModule.java:122)
      \_ installed by: Modules$OverrideModule -&gt; Modules$OverrideModule -&gt; Modules$OverrideModule -&gt; Modules$OverrideModule -&gt; Modules$CombinedModule -&gt; Modules$CombinedModule -&gt; Modules$CombinedModule -&gt; Modules$CombinedModule -&gt; Modules$CombinedModule -&gt; Modules$CombinedModule -&gt; JMAPServerModule -&gt; JMAPModule -&gt; RFC8621MethodsModule

Learn more:
  <a href="https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION">https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION</a>

1 error</pre>
``

**Comment by chibenwa** [comment]
We are missing the binding to the CassandraSubscriptionRepo. We can imo use temporarily the memory version...

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
Really good job finishing this work, thanks a ton @vttranlina ;)

**Comment by Arsnael** [comment]
I will rebase and squash the fixups (and remove the WIP from commit messages)

**Comment by Arsnael** [comment]
Rebased, squashed, changed the memory bindings to the Cassandra ones as well

**Pull request merged**
