### PR TITLE
[UPGRADE] Adopt MIME4J 0.8.8

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by vttranlina — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by Arsnael** [comment]
```
org.apache.james.jmap.memory.cucumber.MemoryGetMessagesMethodTest.Retrieving message should return attachments and html body when some attachments and html message

Expecting actual:
  "html tiramisu ����}�Exif&#0;&#0;II*&#0;&#8;&#0;&#0;&#0; &#0;&#15;&#1;&#2;&#0; &#0;&#0;&#0;�&#0;&#0;&#0;&#16;&#1;&#2;&#0; &#0;&#0;&#0;�&#0;&#0;&#0;&#18;&#1;&#3;&#0;&#1;&#0;&#0;&#0;&#1;&#0;&#0;&#0;&#26;&#1;&#5;&#0;&#1;&#0;&#0;&#0;�&#0;&#0;&#0;&#27;&#1;&#5;&#0;&#1;&#0;&#0;&#0;�&#0;&#0;&#0;(&#1;&#3;&#0;&#1;&#0;&#0;&#0;&#2;&#0;&#0;&#0;1&#1;&#2;&#0; &#0;&#0;&#0;�&#0;&#0;&#0;2&#1;&#2;&#0;&#20;&#0;&#0;&#0;�&#0;&#0;&#0;&#19;&#2;&#3;&#0;&#1;&#0;&#0;&#0;&#2;&#0;&#0;&#0;i�&#4;&#0;&#1;&#0;&#0;&#0;|&#2;&#0;&#0;��&#7;&#0;�&#0;&#0;&#0;�&#0;&#0;&#0;��&#7;&#0;@&#0;&#0;&#0;�&#1;&#0;&#0;��&#7;&#0;�&#0;&#0;&#0;�&#1;&#0;&#0;L*&#0;&#0;Panasonic&#0;DMC-FZ45&#0;&#0;�&#0;&#0;&#0;&#1;&#0;&#0;&#0;�&#0;&#0;&#0;&#1;&#0;&#0;&#0;Ver.1.0 &#0;2014:02:25 10:3"
to be equal to:
  "html  tiramisu"
when ignoring whitespace differences
```

**Comment by Arsnael** [comment]
What about this work?

**Comment by chibenwa** [comment]
Well, I need to investigate...

**Comment by Arsnael** [comment]
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1283/13/testReport/

```
org.apache.james.jmap.memory.cucumber.MemoryGetMessagesMethodTest.Retrieving message should return attachments and text body when some attachments and text message

org.opentest4j.AssertionFailedError: 

Expecting actual:
  "html �PNG &amp#26; &amp#0;&amp#0;&amp#0; IHDR&amp#0;&amp#0;&amp#5;�&amp#0;&amp#0;&amp#2;�&amp#8;&amp#2;&amp#0;&amp#0;&amp#0;��&amp#15; &amp#0;&amp#0;&amp#0; pHYs&amp#0;&amp#0; &amp#19;&amp#0;&amp#0; &amp#19;&amp#1;&amp#0;��&amp#24;&amp#0;&amp#0;&amp#0;&amp#7;tIME&amp#7;�&amp#3; &amp#14;% q�&amp#23;�&amp#0;&amp#0; &amp#0;IDATxڼ�i�m�U 6��Ͻ�5�ޫ�U'��R/&amp#21;*�:&amp#16;6&amp#2;�!��A��&amp#14;�I&amp#6;�c&amp#3;I��1&amp#4;� 70���&amp#4;&amp#19;&amp#27;˄� �a�c�&amp#1;��1�tB&amp#2;&amp#20;Y&amp#18;�o)���W��{���ˏ��9�Z��J��*]�z��s��{�����7�&amp#15;_�����_s�g�u��&amp#24;##)����0&amp#5;��&amp#16;�4M�i����[�V�մ��&amp#0;&amp#0;&amp#1;&amp#16;&amp#0;"P"
to be equal to:
  "html
"
when ignoring whitespace differences
```
Is it related?

**Comment by chibenwa** [comment]
Yes very likely...

**Pull request closed without merging**
