### PR TITLE
JAMES-2586 Postgres - Guice binding EventDTO for DLP Configuration, Quota

### PR DESCRIPTION
**Pull request by vttranlina**
resolve https://github.com/linagora/james-project/issues/5144

### CODE REVIEW

**Comment by Arsnael** [comment]
You duplicated the quota dto related classes to quota-mailing module, you didnt move them :)

**Comment by vttranlina** [comment]
> You duplicated the quota dto related classes to quota-mailing module, you didnt move them :)

updated the commit message

**Comment by Arsnael** [comment]
Why duplicating and not moving them making it generic to implems?

**Comment by vttranlina** [comment]
> Why duplicating and not moving them making it generic to implems? It's DTOs...

as discussed, the "duplicating" commit for postgres, that help us quickly fix the guice binding issue. 
The refactor cassandra to re-use common will be done in another commit

**Review by Arsnael — APPROVED** [review]

**Comment by vttranlina** [comment]
squash fixup

**Pull request merged**
