### PR TITLE
JAMES-3891 Graceful shutdown for queue consumers [3.7.x]

### PR DESCRIPTION
**Pull request by chibenwa**
Graceful shutdown for scheduler is a late addition to the reactor framework, hence I propose an alternative to it.

CF https://github.com/reactor/reactor-core/pull/3089

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by ottoka** [comment]
I wonder about the test failures here. I did a quick test and locally all is well. So is this a matter of timing, test(suite) isolation, or an artifact of the CI build environment?

**Comment by chibenwa** [comment]
Build is especially unstable lately due to recent ci update

**Comment by ottoka** [comment]
That must be it, I just ran the entire webadmin-integration-test suite and all was fine. So is this CI issue going to block the 3.7.4 release?

**Comment by Arsnael** [comment]
We did some fixes on the jenkins build following the CI chaotic upgrade... I just restarted your build, let's hope it goes better this time

**Review by quantranhong1999 — APPROVED** [review]

**Pull request merged**
