### PR TITLE
JAMES-2586 Develocity metrics for postgres branch

### PR DESCRIPTION
**Pull request by quantranhong1999**
We want to see the metrics for postgres-jmap-integration-tests module (which is taking too long)

### CODE REVIEW

**Comment by Arsnael** [comment]
Alright let's see the info we can get :)

**Comment by quantranhong1999** [comment]
> Alright let's see the info we can get :)

In the meantime, at least we still can manually get the tests runtime from build artifact:
[postgres-jmap-its-test-runtime.txt](https://github.com/apache/james-project/files/14596685/postgres-jmap-its-test-runtime.txt)

The total time so far is 32 minutes > 30m timeout.

**Comment by quantranhong1999** [comment]
> Alright let's see the info we can get :)

https://ge.apache.org/s/dqudut5akzxr6/tests/goal/org.apache.james:postgres-jmap-rfc-8621-integration-tests:surefire:test@default-test/overview?collapse-all

**Comment by quantranhong1999** [comment]
> https://ge.apache.org/s/dqudut5akzxr6/tests/goal/org.apache.james:postgres-jmap-rfc-8621-integration-tests:surefire:test@default-test/overview?expand-all

Some actions taken: https://github.com/apache/james-project/pull/2119

**Comment by Arsnael** [comment]
Yes agree. Tests in fact individually look alright, it's just that repeated tests are a time killer.

**Comment by Arsnael** [comment]
Will come when we rebase the branch on master. It filled its purpose, closing it.

**Pull request closed without merging**
