### PR TITLE
JAMES-3897 CrowdSec integration test for SMTP

### PR DESCRIPTION
**Pull request by quantranhong1999**
resolve https://github.com/linagora/james-project/issues/5003

SMTP proxy support with CrowdSec should already be the case.

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]
Looks g ood to me.

Just remove the `third-party/crowdsec/src/test/resources/log/james.log` empty file and we are good :)

**Comment by thanhbv200585** [comment]
There is also integration test for IMAP as well, should we put it CrowdsecIntegrationTest with SMTP or separate them?

**Comment by quantranhong1999** [comment]
> There is also integration test for IMAP as well, should we put it CrowdsecIntegrationTest with SMTP or separate them?

The ticket name says it all.

**Comment by thanhbv200585** [comment]
Read it. Look good to me

**Review by thanhbv200585 — APPROVED** [review]

**Comment by quantranhong1999** [comment]
> Just remove the third-party/crowdsec/src/test/resources/log/james.log empty file and we are good :)

That empty file was intended. During tests, it is used to store James log and share with CrowdSec. After tests, it would be reset to empty again.

Sry I did not find a solution without an empty file yet. Maybe one day I feel bored :D. Or if you have any idea for me ^^.

**Pull request merged**
