### PR TITLE
Various polish for the PGSQL implementation

### PR DESCRIPTION
**Pull request by chibenwa**
- Remove the JVM path locker
 - Renames...

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
Could that have an effect on stress tests with the JPA mixed implem? https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1821/1/testReport/junit/org.apache.james.mailbox.postgres/PostgresMailboxManagerStressTest/testStressTest/

Reruning the build though in case

**Comment by Arsnael** [comment]
Same issue, so related i guess :)

**Comment by Arsnael** [comment]
Can be rebased?

**Comment by chibenwa** [comment]
Can be safely closed as thos commits were integrated in @vttranlina work.

**Pull request closed without merging**
