### PR TITLE
JAMES-1975 Move mailets over from james-jdkim

### PR DESCRIPTION
**Pull request by shrumit**
https://issues.apache.org/jira/browse/JAMES-1975

Added the necessary files and changed the pom as needed. Need guidance on whether this was done correctly.

### CODE REVIEW

**Comment by chibenwa** [comment]
I will trigger a build, and wait over reviews before merging this.

**Comment by shrumit** [comment]
I'm really not sure whether I did this correctly. I just moved over the mailet files and updated the POM. I've run a successful build without tests. When I run a build with tests I get errors unrelated to this, probably something wrong with my local setup.

**Comment by ieugen** [comment]
I'm looking around and found this PR that seems to be waiting for a merge. 
@chibenwa, @shrumit: Should we continue the work and merge? It seems to me like we should.

**Comment by chibenwa** [comment]
Hello @ieugen ,

As far as I can tell, this PR was not passing unit tests.

The move of the mailet from dkim into James Server code had been contributed here https://github.com/linagora/james-project/pull/1709

We should have been notifying it here.

This pull request likely can be closed.

**Comment by ieugen** [comment]
Something has been merged there so I second the closing of this issue. Thank you for your contribution @shrumit . Please let us know if we missed something.

**Pull request closed without merging**
