### PR TITLE
Camel 2.19.1 to 2.19.4

### PR DESCRIPTION
**Pull request by lmilev**
Camel 2.19.1 to 2.19.4 contains dozens of bug fixes and stability improvements.

External resources:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12341575&projectId=12311211

### CODE REVIEW

**Comment by rouazana** [comment]
Thanks again! Here is also the relative build PR: https://github.com/linagora/james-project/pull/1277

**Comment by chibenwa** [comment]
Hi. 

Thanks for your involvement. We definitely need some library updates... That is really welcome!

Camel version 2.20.2 have been released this month. Upgrading to it might be a good move, right?

Cheers,

Benoit

**Comment by lmilev** [comment]
You're correct there is a 2.20.x stream. I chose 2.19.x for better compatibility and less risk.

**Comment by chibenwa** [comment]
Fine for me, but we should rather stick with the latest releases.

Concerning risks, they are mitigated by many integration tests relying on the mailet-container.

**Comment by chibenwa** [comment]
Hi,

This pull request has just been merged.

Thank you again for your dedication toward the James project. If you need help, want to [contribute](https://issues.apache.org/jira/issues/?jql=project%20%3D%20JAMES%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20newbie%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC) [documentation](https://issues.apache.org/jira/issues/?jql=project%20%3D%20JAMES%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20documentation%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC), new [features](https://issues.apache.org/jira/issues/?jql=project%20%3D%20JAMES%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20feature%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC), tests or [bugfix](https://issues.apache.org/jira/issues/?jql=project%20%3D%20JAMES%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20easyfix%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC), please don't hesitate to reach us.

One very last thing: I don't have write access to this repository, hence I can not close this issue. Wouldn't you mind doing it for me? It would avoid me annoying the Apache INFRA team with such simple concerns.

Thanks again,

Cheers,

Benoit

**Comment by lmilev** [comment]
Thank you!

**Comment by chibenwa** [comment]
You are welcome ;-)

**Pull request closed without merging**
