### PR TITLE
[Antora] [PGSQL] Add Extending section to postgresql doc

### PR DESCRIPTION
**Pull request by vttranlina**

### CODE REVIEW

**Review by quantranhong1999 — APPROVED** [review]

**Comment by Arsnael** [comment]
I dont think this will be necessary, with that change coming when the section seems to be made more generic: https://github.com/apache/james-project/pull/2332

**Comment by chibenwa** [comment]
> I dont think this will be necessary, with that change coming when the section seems to be made more generic: https://github.com/apache/james-project/pull/2332

Yes just link the generic section.

**Comment by Arsnael** [comment]
@vttranlina https://github.com/apache/james-project/pull/2332 has been merged

Need to adapt (I know that implies a rebase of postgresql branch on master^^')

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
@vttranlina can you rebase me this a last time please? :)

**Review by quantranhong1999 — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
