### PR TITLE
JAMES-4032 DKIM SMTP hook

### PR DESCRIPTION
**Pull request by chibenwa**
Remains:

 - [x] Unit tests (using mock) on signature validation
 - [x] Integration tests (pass, failure) onto a SMTP server

### CODE REVIEW

**Comment by Arsnael** [comment]
15:45:11,599 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.0:check (check-style) on project james-server-protocols-smtp-dkim: You have 4 Checkstyle violations. -> [Help 1]

**Review by Arsnael — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by Arsnael** [comment]
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2264/7/#showFailuresLink

The S3 tests are unrelated but I think the dkim failed tests are though :)

**Comment by chibenwa** [comment]
Caused by EML being turned from LF to CRLF by git.

I changed the git configuration (last commit) so that we never ever need to worry about this ever again.

ALso I squashed the first commit (force push) only the second commit is new.

**Review by quantranhong1999 — APPROVED** [review]

**Comment by Arsnael** [comment]
Started manually here too... that CI makes me sweat since last week ^^'

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2264/12/

Think related

**Comment by Arsnael** [comment]
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2264/13/

Looks related

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
