### PR TITLE
[ENHANCEMENT] Improve MDN display for JMAP mail RFC-8621

### PR DESCRIPTION
**Pull request by chibenwa**
CF https://github.com/linagora/tmail-flutter/issues/2331#issuecomment-1822230696

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
```
09:45:50,701 [ERROR] Failed to execute goal io.github.evis:scalafix-maven-plugin_2.13:0.1.6_0.9.34:scalafix (scala-check-style) on project james-server-jmap-rfc-8621: Scalafix invoked with errors. Check logs for details. -> [Help 1]
```

**Comment by Arsnael** [comment]
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1809/3/testReport/

Looks related to me

**Review by quantranhong1999 — COMMENTED** [review]
Read it.

**Comment by quantranhong1999** [comment]
```java
sendMDNShouldSendAMDNBackToTheOriginalMessageAuthor – org.apache.james.jmap.memory.MemorySendMDNMethodTest
6s
Error
1 expectation failed.
JSON path [0][1].list[0].hasAttachment doesn't match.
Expected: is <true>
  Actual: <false>

[ERROR] o.a.j.m.i.JamesMailSpooler - Failed 3 processing 1 consecutive times. Mail is requeued with increased failure count.
org.apache.james.mailbox.exception.MailboxRoleNotFoundException: Could not find any mailbox with role 'sent'
	at org.apache.james.jmap.draft.send.PostDequeueDecorator.lambda$moveFromOutboxToSentWithSeenFlag$0(PostDequeueDecorator.java:139)
```

Related?

**Pull request merged**
