### PR TITLE
JAMES-2586 Introduce Single postgres connection factory when disable row level security

### PR DESCRIPTION
**Pull request by vttranlina**

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by chibenwa** [comment]
Can you attache a thread dump?

I would like to see how many threads are allocated to it. I am pretty sure a postgres connection is single thread and would benefit from some sort of pooling. Maybe not a topic for now but something to keep in our mind.

**Comment by Arsnael** [comment]
Conflict, need to rebase. Also @chibenwa demand has not been answered :)

**Comment by vttranlina** [comment]
> Also @chibenwa demand has not been answered :)

yes, I think it is not a high priority, I will lab it in the next few days
Or we can merge it first, and do thread dump later?

**Comment by chibenwa** [comment]
Come on, thread dump with `jstack` should be trivial.

**Comment by vttranlina** [comment]
[threadDump3.txt](https://github.com/apache/james-project/files/13406282/threadDump3.txt)

Thread dump when I tried to provision subscription with `SinglePostgresConnectionFactory`

**Review by chibenwa — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
