### PR TITLE
[JAMES-3698] implements additional delayed messages constraints

### PR DESCRIPTION
**Pull request by jeantil**

### CODE REVIEW

**Comment by jeantil** [comment]
build this please

**Comment by jeantil** [comment]
Surefire fork timeout in some webmin module

**Review by chibenwa — APPROVED** [review]
Looks good to me.

Don't you mind if I ask you to update the corresponding ADR as well?

**Review by Arsnael — APPROVED** [review]

**Comment by jeantil** [comment]
> Don't you mind if I ask you to update the corresponding ADR as well?

done

**Review by chibenwa — APPROVED** [review]
I added a tiny fixup comment regarding the ADR (the scheduled filter topic was missing in the topic list).

Thanks for the fix this looks awesome!

**Review by Arsnael — APPROVED** [review]

**Comment by jeantil** [comment]
>I added a tiny fixup comment regarding the ADR (the scheduled filter topic was missing in the topic list).

Thanks !

**Pull request merged**
