### PR TITLE
[PULSAR] Disable randomly failing test

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by jeantil** [comment]
I don't know, I have been running it until failure and it seems to remain green  (30 iterations for now, I'll let it run while I grab lunch)

**Comment by jeantil** [comment]
I reviewed the test and it relies on a 100ms wait to ensure the filter has been registered. Since the filter registration round-trips through pulsar even in a single instance process, I guess it can sometimes take longer that 100ms on the CI. 

I think I already proposed introducing a dilation/scaling factor for waits on the CI platform.. I'll discuss this more with @mbaechler tomorrow to see if we can come up with a more deterministic approach for tests.
image

**Comment by chibenwa** [comment]
Ok closing, but I'll re-open if the CI fails again here

**Comment by jeantil** [comment]
for reference https://issues.apache.org/jira/browse/JAMES-3696

**Pull request closed without merging**
