### PR TITLE
Avoid sorting PG messages

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
14:47:21,240 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.0:check (check-style) on project apache-james-mailbox-postgres: You have 1 Checkstyle violation. -> [Help 1]
```
Why avoiding the sort btw?

**Comment by vttranlina** [comment]
> Why avoiding the sort btw?

The `retrieveFullContent` fetched bodyContent from ObjectStorage, it is quite heavy.
In the past, I wanted to it concurrency, I used `flatMap`, but the result after `flatmap` was not sorted -> some test cases did not pass.  -> using `.sort` to resolve that.
Looks like we can also resolve that by `flatmapSequential` (ensuring the order inside the reactor)

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
> Why avoiding the sort btw?

Because in order to sort you need to have all the entities sorted at hand first.

**Comment by Arsnael** [comment]
```
09:37:35,066 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.0:check (check-style) on project apache-james-mailbox-postgres: You have 1 Checkstyle violation. -> [Help 1]
```

**Comment by Arsnael** [comment]
Related : https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1964/6/#showFailuresLink

Same as what has been reported before btw => https://github.com/apache/james-project/pull/1964#issuecomment-1920642886

**Review by Arsnael — APPROVED** [review]

**Review by vttranlina — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by Arsnael** [comment]
The build keeps getting timeout?

**Comment by chibenwa** [comment]
Please team care about this as this is a potential production-killer.

**Comment by chibenwa** [comment]
Please team care about this as this is a potential production-killer.

**Pull request closed without merging**
