### PR TITLE
JAMES-3730 Upgrade from Legacy JavaMail to Jakarta Mail 2.0.1/Activation 2.0.1

### PR DESCRIPTION
**Pull request by romainmoreau**
I started with the branch in #939, rebased it, and just did minor fixes so that `mvn clean install` passes, I'm reopening this PR to see if your CI agrees.

I didn't experience the blocking issue referenced in #939, so I assume it was fixed by another commit.

### CODE REVIEW

**Comment by chibenwa** [comment]
Love it, thank you so much!

**Comment by romainmoreau** [comment]
Apart from the commits from the previous PR, the commit I authored contains missing import replacements and code style required by the build.

**Review by Arsnael — APPROVED** [review]
Thank you for finishing this work @romainmoreau , much appreciated :)

**Review by quantranhong1999 — APPROVED** [review]

**Comment by jeantil** [comment]
I have started reiewing in details so far no blockers but a few comments ( possibly pre-existing issues about bouncy castle jdk15on mentions where the main pom references jdk18on) please give me a bit of time to complete my reading

**Review by jeantil — APPROVED** [review]
I would say ok 
but there are quiet a few whitespace changes that seem wrong and metions of jdk15on instead of jdk18on but I think this could be an existing issue as what changed is only the version. I still think it could benefit from a cleanup

**Comment by romainmoreau** [comment]
I fixed your comments @jeantil in 95a98fa and fixed in 781b430 other formatting issues that I found.

The CI build failed because of subethasmtp which was still using the old JavaMail, so it has been updated to the latest version to support Jakarta Mail in c13a1f4.

`mvn clean install` works again for me on my end but the issue doesn't seem to not be deterministic as it was already working before so hopefully this will fix everything.

**Review by chibenwa — APPROVED** [review]
Looks good to me

**Comment by romainmoreau** [comment]
I have pushed a new commit that changes the Jakarta activation and mail implementations from `com.sun` to `org.eclipse.angus`, mainly because:
- The `com.sun.activation` and `com.sun.mail` implementations are now considered to be obsolete and the `org.eclipse.angus` implementations are their successors.
- Pulsar still uses the old `com.sun.activation:javax.activation` implementation and with the previously added `com.sun.activation:jakarta.activation` implementation, it could theoretically have led to class loading conflicts but not with Angus' since it does not have the same class names.

**Review by Arsnael — APPROVED** [review]

**Review by jeantil — APPROVED** [review]

**Comment by romainmoreau** [comment]
I just readded the `org.eclipse.angus:angus-mail` exclusion as its classes are already included in `org.eclipse.angus:jakarta.mail`.

**Pull request merged**
