### PR TITLE
JAMES-3477 Avoid unneeded copies of MimeMessages

### PR DESCRIPTION
**Pull request by chibenwa**
We needlessly copy mime messages in a few occasions:
 - After receiving an email via SMTP and enqueuing it
 - When instantiating a Mail via JMAP
 - When dequeuing a mail

 In all these cases there is no need to proceed with the defensive copy
 in MailImpl::setMail as we just instanciated it and won't keep a reference.

The COW approach did hide this pitfall.

With these changes, the 'always copy' code is on par performance wise with the 'COW' one, without its drawbacks.

Identified while benching https://github.com/apache/james-project/pull/285

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
Still getting the 

```
05:02:42.728 [ERROR] o.a.j.m.i.c.CamelProcessor - Exception calling Sieve: Mail message to be spooled cannot be null.
java.lang.NullPointerException: Mail message to be spooled cannot be null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at org.apache.james.transport.mailets.jsieve.delivery.SieveExecutor.execute(SieveExecutor.java:120)
	at org.apache.james.transport.mailets.Sieve.service(Sieve.java:75)
	at org.apache.james.mailetcontainer.impl.camel.CamelProcessor.process(CamelProcessor.java:77)
	at org.apache.james.mailetcontainer.impl.camel.CamelMailetProcessor$MailetContainerRouteBuilder.handleMailet(CamelMailetProcessor.java:176)
	at org.apache.james.mailetcontainer.impl.camel.CamelMailetProcessor$MailetContainerRouteBuilder.lambda$configure$0(CamelMailetProcessor.java:153)
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
```

:-(

**Comment by chibenwa** [comment]
On master:

Screenshot from 2021-02-17 08-01-01

On this branch:

Screenshot from 2021-02-17 08-02-40

Sorry for the delays, I had to reboot Linagora's James' bench CI, and it did not work out of the box.

**Comment by chibenwa** [comment]
I will now merge build enhancements, and relaunch a build here, and eventually merge this.

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
:green_apple: on the CI

**Comment by chibenwa** [comment]
I merged this work.

**Pull request closed without merging**
