### PR TITLE
JAMES-2586 - CLEAN CODE -  Guice binding for Postgres User Repository modules

### PR DESCRIPTION
**Pull request by vttranlina**
- Making it easier to install the binding when a user chooses this option.

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
Hmmm are you sure? 

https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1919/2/

**Comment by vttranlina** [comment]
> Hmmm are you sure?
> 
> https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1919/2/

```
Exception in thread "docker-java-stream--1274020268" java.lang.NoClassDefFoundError: Could not initialize class org.apache.james.backends.postgres.DockerPostgresSingleton

```
It looks like  unstable ci

**Review by quantranhong1999 — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by vttranlina** [comment]
Weird, Mvn command was passed on my local
```
Exception in thread "docker-java-stream--571842516" java.lang.NoClassDefFoundError: Could not initialize class org.apache.james.backends.postgres.DockerPostgresSingleton
```
The `pg-app` already import dependency `<artifactId>apache-james-backends-postgres</artifactId>`

let me rebase

**Comment by Arsnael** [comment]
Keeps failing on that though on the CI, might want to investigate a bit more... or we drop that refactoring for now, not that necessary?

**Comment by quantranhong1999** [comment]
> Keeps failing on that though on the CI, might want to investigate a bit more... or we drop that refactoring for now, not that necessary?

I helped Tung running tests locally, they are green.

It keeps failing on CI worker builds22 though:
`Running on builds22 in /home/jenkins/jenkins-agent/workspace/james_ApacheJames_PR-1919`
-> Likely CI worker issue. Maybe we should try another PR to fire build on a new worker.

BTW [Some errors cause a NoClassDefFoundError and the real error is hidden](https://github.com/testcontainers/testcontainers-java/issues/1872). We likely have been tricked by test containers all the time thinking that was a missing dependency issue.

**Comment by vttranlina** [comment]
>  or we drop that refactoring for now, not that necessary?

It should be better if yes.
It makes sense for case user module chooser (ex: tmail-backend), 
you can re-run it one more time? if it still fails, I will create another PR.

**Comment by Arsnael** [comment]
> BTW https://github.com/testcontainers/testcontainers-java/issues/1872. We likely have been tricked by test containers all the time thinking that was a missing dependency issue.

Good catch... I was starting to think it was probably hiding something else anyways cause:
- the postgresql build is short and just compiles a few modules
- I noticed the same sometimes as well on tmail-backend build on our own CI

So more likely the problem comes with our build and testcontainers, and it's clearly a tricky one.

Maybe timeout during init for cassandra?

**Pull request merged**
