### PR TITLE
JAMES-3771 Migrate to opensearch 2.1 and its high level rest java client

### PR DESCRIPTION
**Pull request by Arsnael**
As I don't have a clue on what's going on with the build in https://github.com/apache/james-project/pull/1061, I'm trying this alternative... If I have the same issue, maybe the problem is with the docker image and how we init it. If not, then the problem could be lying somewhere in the migration code... 

But I start to feel desperate TBH

### CODE REVIEW

**Comment by Arsnael** [comment]
A green build... amazing...

**Comment by chibenwa** [comment]
Should we merge this, and make the full-rest-client adoption a follow up rework?

Cc @Arsnael ?

**Comment by Arsnael** [comment]
> Should we merge this, and make the full-rest-client adoption a follow up rework?

I guess we can yes. I would prefer though to rebase it first as it's been a while this passed

**Comment by chibenwa** [comment]
Please go ahead.

**Review by quantranhong1999 — APPROVED** [review]

**Comment by vttranlina** [comment]
read it

**Review by chibenwa — APPROVED** [review]
As it allow moving on the OpenSearch topic.

As I understand getting rid of the high-level rest java client itself would take more time...

**Pull request merged**
