### PR TITLE
JAMES-2993 WebAdmin markdown - Fix href Administrating messages

### PR DESCRIPTION
**Pull request by vttranlina**
- OLD: https://james.apache.org/server/manage-webadmin.html#Administrating_messages  (not jump to the target line)
- NEW: https://james.apache.org/server/manage-webadmin.html#Administrating_Messages  (working)

### CODE REVIEW

**Comment by chibenwa** [comment]
Working... On github? Or while vompiling the website?

THe target is to have the website  links working, having github formatting is a nice side effect.

**Comment by vttranlina** [comment]
> The target is to have the website links working, having github formatting is a nice side effect.
Sorry, I don't understand what you mean.
I don't sure how to auto-generate the HTML website for James. 
I search it in James' source code, and only the markdown file has "href" atribute.

**Comment by chibenwa** [comment]
> I don't sure how to auto-generate the HTML website for James.

We use https://github.com/apache/james-project/blob/master/src/site/Dockerfile

The goal is to have the resulting html  without dead links (we do not really care about the github page...)

**Comment by chibenwa** [comment]
And you are right: it fixes the resulting HTML ;-)

**Review by chibenwa — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
