### PR TITLE
[REFACTOR] moves data-api configuration files to test sources

### PR DESCRIPTION
**Pull request by jeantil**
By being in the main sources, they were automatically available on the
classpath, potentially masking missing files and applying incorrect or
involuntary default configuration.

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Comment by jeantil** [comment]
So it did surface a few failing tests in memory-app, looks like it was depending on the classpath provided usersrepository.xml

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
Hello @jeantil 

I am not sure we need to constantly rebase on master, especially for "easy" work...

Also the build stability looks better now ...

**Comment by jeantil** [comment]
I might not for a different type of work, but this specific MR can (and has) triggered test failures in unanticipated modules, I really don't feel confident enough to merge it without a green CI. since the cassandra-related failures could have hidden more failures related to this work, I rebased to get a new CI build once I saw the MR on test stability got merged

**Comment by jeantil** [comment]
test this please

time out failures the build didn't run on the modules I care about :/

**Comment by chibenwa** [comment]
This one is 100% related https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1065/14/testReport/junit/org.apache.james.cli/MailboxManageTest/mailboxExistWithInvalidMailboxNameShouldFail/

IMO this one could be too https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1065/14/testReport/junit/org.apache.james.transport.mailets/StripAttachmentTest/stripAttachmentShouldPutAttachmentsInMailAttributeWhenConfiguredForIt/

**Comment by jeantil** [comment]
I'm glad I didn't merge right away :) I'll look into it tomorrow

**Comment by jeantil** [comment]
So I had a look tonight and got a few fixes in. 
Doing so, I met an interesting side issue : 
`MemoryModularizeJmapRFC8621AuthenticationStrategyContract` passes individually but not when I run all the tests in `jmap-rfc-8621-integration-tests-common` but it is not failing on CI 

I am not sure what's going on here exactly...

**Comment by chibenwa** [comment]
>  one rabbit error `testRenameITALY – org.apache.james.mpt.imapmailbox.rabbitmq.RabbitMQRenameTest on build 17

Fixed :-p https://github.com/apache/james-project/pull/1071/commits/8fd42ab96de2c5f1c7722692d148aa139362fd5e

> I still don't feel confident I caught all errors caused by my removing these config files from the classpath so I will keep rebasing and/or rerunning the build until I get a green one

:+1:

**Review by Arsnael — APPROVED** [review]
Well it's green now :)

**Pull request merged**
