### PR TITLE
JAMES-3026 Fix OpenJPA transaction memory leak

### PR DESCRIPTION
**Pull request by provirus**

### CODE REVIEW

**Comment by provirus** [comment]
I was thinking the same. Will do

**Comment by chibenwa** [comment]
Nice! Thanks :-)

**Comment by provirus** [comment]
Updated. Thanks

**Comment by chibenwa** [comment]
Hi,

This pull request has just been merged.

One very last thing: I don't have write access to this repository, hence I can not close this issue. Wouldn't you mind doing it for me? It would avoid me annoying the Apache INFRA team with such simple concerns.

Thanks again,

Cheers,

Benoit

**Pull request closed without merging**
