### PR TITLE
JAMES-3225 Fasten build by dropping irrelevant server/protocols/jmap-…

### PR DESCRIPTION
**Pull request by chibenwa**
…draft-integration-testing/cassandra integration tests

According to https://builds.apache.org/blue/organizations/jenkins/james%2FApacheJames/detail/PR-264/58/pipeline/83 we gain 33:48 min + 34:07 min allowing the Apache build to get down 6h.

These tests are redundant with `server/protocols/jmap-draft-integration-testing/rabbitmq-jmap-draft-integration-testing`

Furthermore (even if it *might* be considered irrelevant by some) I do consider the Cassandra + ES without a distributed messaging technology irrelevant as it do not address the scalability / high availability promise, hence running expensive integration tests for this combination seems like a non sense to me.

As a proof, webadmin integration tests and JMAP RFC-8621 integration tests are not run against this app. Doing the same for soon-to-be-deprecated JMAP draft would make sense to me.

### CODE REVIEW

**Comment by mbaechler** [comment]
could you rebase this PR ?

**Comment by chibenwa** [comment]
Congrats!

Now let's work together to get the build below 3h :-)

**Comment by chibenwa** [comment]
Achieved a :green_apple: build on Linagora CI

**Comment by chibenwa** [comment]
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-289/4 is :green_apple:

**Review by jeantil — APPROVED** [review]

**Review by mbaechler — APPROVED** [review]

**Pull request merged**
