### PR TITLE
JAMES-2586 [PGSQL] Optimize Mailbox/Message Mapper 

### PR DESCRIPTION
**Pull request by vttranlina**

### CODE REVIEW

**Comment by chibenwa** [comment]
Please back those changes with gatling test runs... Before and after...

**Review by Arsnael — APPROVED** [review]

**Review by hungphan227 — APPROVED** [review]

**Comment by chibenwa** [comment]
I'll approuve when provided benchmarks backing this change ;-)

**Comment by vttranlina** [comment]
> I'll approuve when provided benchmarks backing this change ;-)

yes, I'm doing it.
It takes time to fix some guice app and provision sample data. 
A lot of docker crash on my pc when try provision 5k users :D

**Comment by quantranhong1999** [comment]
Just a remark: did you warm up James before testing?

BTW 5k users looks too easy on your "super" machine :D

**Comment by vttranlina** [comment]
> Just a remark: did you warm up James before testing?

I ran the Gatling test with duration=5m before real test

**Comment by Arsnael** [comment]
> A lot of docker crash on my pc when try provision 5k users :D

don't hesitate to use james-charge-01 instead then :)

**Review by chibenwa — APPROVED** [review]

**Comment by chibenwa** [comment]
If you look specificly "fetchHeaders" and "status" the gains are clear.

**Review by quantranhong1999 — APPROVED** [review]

**Comment by vttranlina** [comment]
rebase master & squash

**Pull request merged**
