### PR TITLE
JAMES-2586 Update PostgresBase in jmap postgres integration tests

### PR DESCRIPTION
**Pull request by hungphan227**

### CODE REVIEW

**Comment by Arsnael** [comment]
Reason for switching from scanning to opensearch on those tests?

**Comment by hungphan227** [comment]
> Reason for switching from scanning to opensearch on those tests?

I saw DistributedBase did the same thing. Moreover, because Postgres version of james still use opensearch, it is better to include open search in integration tests, isn't it?

**Comment by chibenwa** [comment]
> Moreover, because Postgres version of james still use opensearch, it is better to include open search in integration tests, isn't it?

What is the time difference running the whole test suite? In scanning? With OpenSearch?

TBH Use OpenSearch only for Email/query if you want, but I think it increase run time too much with no clear benefits on other tests.

**Comment by Arsnael** [comment]
I agree with @chibenwa 

Also keep in mind that => distributed is designed to be deployed alongside opensearch, postgres app not necessarily

**Comment by vttranlina** [comment]
read it, nothing to add

**Pull request closed without merging**
