### PR TITLE
[UPGRADE] MIME4J 0.8.7 -> 0.8.9

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by quantranhong1999 — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
What about this work?

**Comment by chibenwa** [comment]
- [ ] Needs performance tests IMO
 
 We could merge the last :green_apple: commit.
 
 More time would be needed to adopt good resource management for MIME4J inside the JMAP layers.

**Comment by Arsnael** [comment]
It's green... do we merge this?

**Comment by chibenwa** [comment]
Let's do a performance test first ;-)

**Comment by chibenwa** [comment]
# IMAP

## Master branch

Image

## Mime4j-0.8.9

Image

It's better...

**Pull request merged**
