### PR TITLE
Build stability

### PR DESCRIPTION
**Pull request by Arsnael**
It seems to block somehow in logs around memory jmap integration tests and webadmin integration tests (but I might be wrong as we play tests in parallel)

First is we tagged a test class unstable but we don't make the distinction in the pom of the module

Second is... I don't know for me it breaks locally, I find it weird it passes on the CI. Those values were modified with DKIMHook PR but not sure to get really why... Anyways let's just see what the CI thinks.

### CODE REVIEW

**Comment by chibenwa** [comment]
> [Build] Fix some local errors on jmap integration tests 

Review git settings.

**Comment by chibenwa** [comment]
Ok for the other commit though

**Comment by Arsnael** [comment]
> Review git settings.

Meaning? Detail? I'm on the latest code and I recompiled the all project with maven before running tests, what git settings are you talking about exactly?

**Comment by vttranlina** [comment]
> 
> Meaning? Detail? I'm on the latest code and I recompiled the all project with maven before running tests, what git settings are you talking about exactly?

You modified the code from `\\r\\n` to `\\n`, it related to the configure the CRLF/LF (autocrlf) setting in Git, which can be configured globally or specifically for the James project.

**Comment by Arsnael** [comment]
Thank you for the explanation

**Pull request merged**
