### PR TITLE
[UPGRADE] RabbiMQ libraries, Redis libraries, Tika, ClamAV, Rspamd, Crowdsec image

### PR DESCRIPTION
**Pull request by vttranlina**

### CODE REVIEW

**Review by quantranhong1999 — APPROVED** [review]

**Comment by chibenwa** [comment]
Rebase needed

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
Rebase needed

**Comment by Arsnael** [comment]
So sorry, can you rebase for the documentation part that got moved back to root folder?

**Review by Arsnael — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by Arsnael** [comment]
Was green before and the only bit that got rebased was doc. I consider it good for merging.

**Pull request merged**
