### PR TITLE
JAMES-3187 Add webadmin enabled by default to jpa-guice docker image

### PR DESCRIPTION
**Pull request by chibenwa**
Relates to https://github.com/apache/james-project/pull/191/commits/5905a1dfad8c4e97a7a0fb34b5201b66a23bec73#r426520378

### CODE REVIEW

**Comment by chibenwa** [comment]
> I don't understand why we want jpa image to be insecure by default.

1. All other images enables Webadmin by default because...
2. ... as long as you don't expose the port the service is not available outside.

Note that port binding can be bound to a specific interface for instance loopback, allowing us to achieve both user convenience and safety. See https://github.com/apache/james-project/pull/196

Why do something different for JPA?

Should we disable WebAdmin everywhere instead?

**Comment by mbaechler** [comment]
> > I don't understand why we want jpa image to be insecure by default.
> 
>     1. All other images enables Webadmin by default because...
> 
>     2. ... as long as you don't expose the port the service is not available outside.
> 
> 
> Note that port binding can be bound to a specific interface for instance loopback, allowing us to achieve both user convenience and safety. See #196

A bit optimistic ...
 
> Why do something different for JPA?
> 
> Should we disable WebAdmin everywhere instead?

... but if it's already the case, let's use it here too

**Comment by chibenwa** [comment]
(Please note that along with this work, I open a ticket to add basic auth to webadmin, based on usersrepository.xml aministratorId  enabling us a easier aythentication setup and eventually addressing this issue)

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
