### PR TITLE
JAMES-4077 Renaming LuceneMemorySearchHighlighter -> LuceneSearchHighlighter & add new Lucene File system test

### PR DESCRIPTION
**Pull request by vttranlina**
The `LuceneMemorySearchHighlighter` only use lucene highlight api, it's nothing special just for memory.

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by quantranhong1999** [comment]
`Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.0:check (check-style) on project apache-james-mailbox-tika: You have 1 Checkstyle violation.`

**Review by quantranhong1999 — APPROVED** [review]

**Comment by vttranlina** [comment]
weird, "tika", I didn't change anything to that module

I just rebuilt locally, and it was successful.
Screenshot_20241008_090506

**Comment by quantranhong1999** [comment]
@Arsnael can you help merge this one to fix the master build: https://github.com/apache/james-project/pull/2440

**Comment by Arsnael** [comment]
The tika PR was merged while no build was done (it seems there was some issues with the ci yesterday, didnt look very stable)

We should be more careful when merging things

**Comment by vttranlina** [comment]
rebase master

**Comment by Arsnael** [comment]
Can rebase

**Pull request merged**
