### PR TITLE
[IMPROVEMENT] Prevent RMI from doing System.gc every hour

### PR DESCRIPTION
**Pull request by chibenwa**
Screenshot from 2022-06-27 15-40-46

Suspicious! GC every hour with JMX activated... I'll shoot down the usual suspect.

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
> :exploding_head: 

Not surprised that's a big classic in Devoxx JVM talks. I listen to that when washing dishes....

**Comment by jeantil** [comment]
i do sometimes too but clearly not enough. I would be very curious to understand the rationale that drove to scheduling a gc every hour ...

**Comment by chibenwa** [comment]
Likely some long living connections  with some churns.

Long living connections cause the old gen to fill up.

And the churn turns those old gen objects into garbadges.

I bet the intent is to try to achieve reasonnable pause time by forcing periodic GCs rather than let a huge GC pause build up. THough debatable this 'could' make sense for JMX intensive apps.

Now in james context we only use JMX for the CLI and in the heap dump I worked with I never even come to read 'rmi' or 'jmx' thus I believe that for James this GC pause is highly irrelevant.

Also I came across some comments in Cassandra source code explicitly disabling this : https://github.com/apache/cassandra/blob/39e89fd636ee4343eb2201820da87881cbc749e2/src/java/org/apache/cassandra/utils/JMXServerUtils.java#L110

**Comment by jeantil** [comment]
>THough debatable this 'could' make sense for JMX intensive apps
sounds like premature optimization built-in right into the JDK :p

**Pull request merged**
