### PR TITLE
Upgraded from Legacy JavaMail to Jakarta Mail 2.0.1/Activation 2.0.1

### PR DESCRIPTION
**Pull request by glennosss**
Upgraded from Legacy JavaMail to Jakarta Mail 2.0.1/Activation 2.0.1;

- Jakarta Mail - https://github.com/eclipse-ee4j/mail/releases
- Jakarta Mail Activation - https://github.com/eclipse-ee4j/jaf/releases

Also upgraded from Bouncy Castle 'bcmail' (Legacy JavaMail) to Bouncy Castle 'bcjmail' (Jakarta Mail);
- Read https://github.com/bcgit/bc-java/issues/832 for more information

More specifically;

- 'com.sun.mail:jakarta.mail:2.0.1' from 'com.sun.mail:javax.mail' / 'javax.mail:mail' / 'org.apache.geronimo.javamail:geronimo-javamail_1.4_mail'
- 'com.sun.activation:jakarta.activation:2.0.1' from 'com.sun.activation:javax.activation' / 'javax.activation:activation' / 'javax.activation:javax.activation-api'
- 'org.bouncycastle:bcjmail-jdk15on' from 'org.bouncycastle:bcmail-jdk15on'

Most of this change involved replacing the following strings;

- import javax.mail. -> import jakarta.mail.
- import javax.activation. -> import jakarta.activation.
- import static javax.mail. -> import static jakarta.mail.

Also updated license files as well.

### Assistance required to complete pull request

A majority of my time was spent fixing checkstyle issues which I believe are mostly resolved - there may be one or two remaining checkstyle issues because I wasn't able to build the entire project successfully. Please excuse the minor change to `checkstyle.xml` to ImportOrder groups - "javax" changed to "javax,jakarta" - it was done to make the review process as easy as possible (import orders would have had to change radically without this making review harder). If it's a big deal for any one, I suggest changing it in a later pull request - otherwise it would make this pull request far too unwieldy.

I'm hoping the project's maintainers can continue this pull request on my behalf from here. But as I said I'm confident this change is 99% complete. Thanks in advance for your support.

### CODE REVIEW

**Comment by glennosss** [comment]
Created Jira: https://issues.apache.org/jira/browse/JAMES-3730

I'm keen to get some movement on this! Thanks guys :)

**Comment by chibenwa** [comment]
Hello. This is much welcome.

> If it's a big deal for any one, I suggest changing it in a later pull request 

Not an issue to me.

> I'm hoping the project's maintainers can continue this pull request on my behalf from here. But as I said I'm confident this change is 99% complete. Thanks in advance for your support.

Thanks for the contribution. I'' then force push to solve the rebase conflict.

**Comment by chibenwa** [comment]
Ok, rebased. We are in for a ride. Let's wait what CI have to say!

**Review by chibenwa — COMMENTED** [review]
I checked I do not think there is breking changes for FileMailRepository. This would be woth checking before merging.



I did a full review of the changeset which took me quite some time. We need to avoid force pushes on this work as much as possible...

**Review by Arsnael — COMMENTED** [review]
Nothing to add, thanks a lot for this contribution, awesome work!

**Comment by chibenwa** [comment]
We have some issues...

In `org.apache.james.CassandraMailRepositoryIntegrationTest.deniedSenderMailShouldBeStoredInCassandraMailRepositoryWhenConfigured{GuiceJamesServer}` for instance.

```
08:05:59.211 [ERROR] o.a.j.m.i.ProcessorImpl - Exception calling Bounce: class org.apache.geronimo.javamail.handlers.MultipartHandler cannot be cast to class jakarta.activation.DataContentHandler (org.apache.geronimo.javamail.handlers.MultipartHandler and jakarta.activation.DataContentHandler are in unnamed module of loader 'app')
java.lang.ClassCastException: class org.apache.geronimo.javamail.handlers.MultipartHandler cannot be cast to class jakarta.activation.DataContentHandler (org.apache.geronimo.javamail.handlers.MultipartHandler and jakarta.activation.DataContentHandler are in unnamed module of loader 'app')
```

Here the fix is to get rid of `geronimo` I imagine.

```
$ grep geronimo * -R | grep pom.xml
server/apps/spring-app/pom.xml:                    <groupId>org.apache.geronimo.javamail</groupId>
server/apps/spring-app/pom.xml:                    <artifactId>geronimo-javamail_1.4_mail</artifactId>
server/mailet/dkim/pom.xml:                    <groupId>org.apache.geronimo.javamail</groupId>
server/mailet/dkim/pom.xml:                    <artifactId>geronimo-javamail_1.4_mail</artifactId
```

Stacktrace:

```
16:14:03.252 [ERROR] o.a.j.m.i.ProcessorImpl - Exception calling Bounce: class org.apache.geronimo.javamail.handlers.MultipartHandler cannot be cast to class jakarta.activation.DataContentHandler (org.apache.geronimo.javamail.handlers.MultipartHandler and jakarta.activation.DataContentHandler are in unnamed module of loader 'app')
java.lang.ClassCastException: class org.apache.geronimo.javamail.handlers.MultipartHandler cannot be cast to class jakarta.activation.DataContentHandler (org.apache.geronimo.javamail.handlers.MultipartHandler and jakarta.activation.DataContentHandler are in unnamed module of loader 'app')
	at jakarta.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:601)
	at jakarta.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:554)
	at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:590)
	at jakarta.activation.DataHandler.writeTo(DataHandler.java:289)
	at jakarta.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1670)
	at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1888)
	at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1862)
	at org.apache.james.server.core.MimeMessageWrapper.<init>(MimeMessageWrapper.java:158)
	at org.apache.james.server.core.MailImpl.setMessage(MailImpl.java:505)
	at org.apache.james.transport.mailets.redirect.ProcessRedirectNotify.createAlterMessage(ProcessRedirectNotify.java:126)
	at org.apache.james.transport.mailets.redirect.ProcessRedirectNotify.process(ProcessRedirectNotify.java:68)
	at org.apache.james.transport.mailets.Bounce.service(Bounce.java:246)
	at org.apache.james.mailetcontainer.impl.ProcessorImpl.process(ProcessorImpl.java:73)
```

JDKIM itself should likely be proted to jakarta.mail ?

The spring app should likely be able to drop `org.apache.geronimo.javamail`...

**Comment by glennosss** [comment]
I'm having to move onto other projects. So good luck with the project guys. I'll leave this pull request open - feel free to do whatever you want with it - hope it goes well guys :-)

**Comment by chibenwa** [comment]
Thanks for your contributions so far!

**Comment by jeanouii** [comment]
Hi,

I'm moving Geronimo Specs and Mail provider to Jakarta Mail and Activation.
We depend on James. Is there any chance to get James to be supporting new jakarta package?

**Comment by jeanouii** [comment]
Do you need help to finish this PR or from Geronimo?

**Comment by chibenwa** [comment]
> We depend on James. Is there any chance to get James to be supporting new jakarta package?

This would be a bracking change but yes, eventually.

> Do you need help to finish this PR or from Geronimo?

Yes it would be MUCH welcomed!

**Comment by chibenwa** [comment]
Is there any plan to carry on this work?

**Comment by chibenwa** [comment]
No answer, closing.

Reopen if relevant.

**Pull request closed without merging**
