### PR TITLE
JAMES-3798 fix bounce exception when no date header is present

### PR DESCRIPTION
**Pull request by ouvtam**

### CODE REVIEW

**Review by chibenwa — COMMENTED** [review]
Thanks a lot for the contribution!

Having a unit test for MailModifier would be awesome, if you have 5 minutes to devote to it!

**Comment by chibenwa** [comment]
I propose the following test.

Cheers, and thanks for the contribution.

**Review by Arsnael — APPROVED** [review]
Looks good to me. Thank you for the kind contribution :)

**Review by quantranhong1999 — APPROVED** [review]

**Comment by ouvtam** [comment]
@chibenwa thanks for adding the test. I was just about to start writing the unit test.

**Pull request merged**
