### PR TITLE
JAMES-2586 Create AttachmentIdFactory

### PR DESCRIPTION
**Pull request by hungphan227**
This PR is to refactor AttachmentID and create AttachmentIdFactory in order to create new AttachmentID implementation in postgresql  branch

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Comment by Arsnael** [comment]
```
12:15:19,569 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.0:check (check-style) on project apache-james-mailbox-jpa: You have 2 Checkstyle violations. -> [Help 1]
```

**Comment by quantranhong1999** [comment]
Any ticket number or tag for this work?

**Comment by hungphan227** [comment]
> Any ticket number or tag for this work?

Should I put JAMES-2586 to this? The purpose of this PR is only refactoring code in master and creating AttachmentIdFactory so that I can implement new AttachmentId for postgres app

**Comment by quantranhong1999** [comment]
> Should I put JAMES-2586 to this? The purpose of this PR is only refactoring code in master and creating AttachmentIdFactory so that I can implement new AttachmentId for postgres app

My guess that is OK.

**Review by Arsnael — APPROVED** [review]

**Comment by hungphan227** [comment]
> java.lang.ExceptionInInitializerError
> 	at org.apache.james.backends.opensearch.ClientProviderImplConnectionAuthESOverrideTrustStoreTest.<clinit>(ClientProviderImplConnectionAuthESOverrideTrustStoreTest.java:34)
> 	
> Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image opensearchproject/opensearch:2.8.0
> 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
> 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
> 	at org.apache.james.util.docker.DockerContainer.start(DockerContainer.java:156)
> 	at org.apache.james.backends.opensearch.DockerOpenSearch$NoAuth.start(DockerOpenSearch.java:171)
> 	at org.apache.james.backends.opensearch.DockerOpenSearch$WithAuth.start(DockerOpenSearch.java:247)
> 	at org.apache.james.backends.opensearch.DockerAuthOpenSearchSingleton.<clinit>(DockerAuthOpenSearchSingleton.java:26)
> 	... 62 more
> Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
> 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
> 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
> 	... 67 more
> Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
> 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:553)
> 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
> 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
> 	... 68 more
> Caused by: java.lang.IllegalStateException: Wait strategy failed. Container exited with code 1
> 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:523)
> 	... 70 more
> Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:36125/ should return HTTP 200)
> 	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:320)
> 	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
> 	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:964)
> 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490)
> 	... 70 more
> Caused by: org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
> 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:54)
> 	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:252)
> 	... 73 more
> Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection refused
> 	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$null$6(HttpWaitStrategy.java:312)
> 	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
> 	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$waitUntilReady$7(HttpWaitStrategy.java:257)
> 	at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:43)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> Standard Output
> 08:02:15.724 [ERROR] t.o.8.0 - Could not start container
> java.net.ConnectException: Connection refused

No idea why this error occur

**Comment by quantranhong1999** [comment]
> No idea why this error occur

likely just unstable CI

**Comment by Arsnael** [comment]
That's the usual testcontainer bug issue that we have been discussing about so many times already, yeah not related to your PR. I will restart the build

**Pull request merged**
