### PR TITLE
JAMES-3470 Bind Cassandra changes DAOs in singleton scope

### PR DESCRIPTION
**Pull request by chibenwa**
This avoids re-preparing several time the same Cassandra queries

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by LanKhuat — APPROVED** [review]

**Review by jeantil — APPROVED** [review]

**Comment by jeantil** [comment]
I notice you updated this in the casandra guice, does it make sense with regards to the intention to deprecate it mentionned in https://mail-archives.apache.org/mod_mbox/james-server-dev/202102.mbox/%3C128f2f1b-ccaa-ee3e-be5c-1f88fd8f76da%40apache.org%3E

**Comment by chibenwa** [comment]
cassandra modules will not be deprecated in my proposition, only the Cassandra + ElasticSearch + James combinaison>

It will keep being used by the Distributed server (Cassandra + ElasticSearch + S3 + RabbitMQ)>

@jeantil does this explicits your mis-understanding?

**Comment by jeantil** [comment]
ok ! thanks for the explanation :)

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
