### PR TITLE
JAMES-4046 Upgrade Lucene

### PR DESCRIPTION
**Pull request by quantranhong1999**
resolve https://github.com/linagora/james-project/issues/5001

status: fine at version 6

### CODE REVIEW

**Review by Arsnael — COMMENTED** [review]
Read it, nothing to comment so far.

Seeing that latest release of Lucene is 9.11... good luck :)

**Comment by quantranhong1999** [comment]
I am starting to get lost debugging the `testSearchAtomsUS` MPT test.

I confirm that this test failed from Lucene 4.x already.

```
C: A83 STORE 1:9  +FLAGS (\FLAGGED)
S: \* 1 FETCH \(FLAGS \(\\Flagged \\Recent\)\)
S: \* 2 FETCH \(FLAGS \(\\Flagged \\Recent\)\)
S: \* 3 FETCH \(FLAGS \(\\Flagged \\Recent\)\)
S: \* 4 FETCH \(FLAGS \(\\Flagged \\Recent\)\)
S: \* 5 FETCH \(FLAGS \(\\Flagged \\Recent\)\)
S: \* 6 FETCH \(FLAGS \(\\Flagged \\Recent\)\)
S: \* 7 FETCH \(FLAGS \(\\Flagged \\Recent\)\)
S: \* 8 FETCH \(FLAGS \(\\Flagged \\Recent\)\)
S: \* 9 FETCH \(FLAGS \(\\Flagged \\Recent\)\)
S: A83 OK STORE completed\.

C: A84 STORE 1:4  +FLAGS (\ANSWERED)
S: \* 1 FETCH \(FLAGS \(\\Answered \\Flagged \\Recent\)\)
S: \* 2 FETCH \(FLAGS \(\\Answered \\Flagged \\Recent\)\)
S: \* 3 FETCH \(FLAGS \(\\Answered \\Flagged \\Recent\)\)
S: \* 4 FETCH \(FLAGS \(\\Answered \\Flagged \\Recent\)\)
S: A84 OK STORE completed\.

C: A85 STORE 10:14  +FLAGS (\ANSWERED)
S: \* 10 FETCH \(FLAGS \(\\Answered \\Recent\)\)
S: \* 11 FETCH \(FLAGS \(\\Answered \\Recent\)\)
S: \* 12 FETCH \(FLAGS \(\\Answered \\Recent\)\)
S: \* 13 FETCH \(FLAGS \(\\Answered \\Recent\)\)
S: \* 14 FETCH \(FLAGS \(\\Answered \\Recent\)\)
S: A85 OK STORE completed\.
```

After this script, only messages 10 to 14 are added the `Answered` flag, while it is not the case for messages 1 to 4. Messages 1 to 4 after this script still stuck with only the `Flagged` flag.

The weird thing is if we do not update the  `Flagged` flag for messages 1 to 4 in the first place, then setting the `Answer` flag for them is OK.

My feeling is we have an issue updating the flag for the messages that already have a flag. But I could not progress more in that direction...

**Comment by chibenwa** [comment]
Have you checked for race conditions? I suspect the lucene indexes updates not to be idempotent...

**Comment by quantranhong1999** [comment]
> Have you checked for race conditions? 

Synchronized keyword does not solve the issue for example.

> With the UpdatedFlags ad hand we can instead subtilly mix added flags / deletes flags?
BTW we might adopt a similar indempotent friendly way to apply updates into OpenSearch too I believe...

It is likely not impossible with Lucene or at least our case for partial update (Lucene supports partially update only NUMERIC and BINARY field type while our flags need to be STRING to easily query). `Lucene does not provide a direct API to update just a part of a document. The typical approach in Lucene is to delete the old document and add a new one with the updated fields. This is because Lucene's indexing structure does not allow for in-place updates of individual fields without reindexing the entire document.`


> My feeling is we have an issue updating the flag for the messages that already have a flag.

  So after a `.updateDocument` call:
   - If I use the old `IndexReader`, I see no change on the document but can search for the document.
   - If I use the new `IndexReader` (to try to get the latest snapshot of the index), I see no change on the document and even can not search for the document.

  I tried to make `IndexWriter` commit everywhere and open new `IndexReader` but can not see the change got reflected (right away). And somehow the update is really laggy.
e.g:
- after we set the `FLAGGED` flag on the message, we see the message has no flag.
- after we add the `ANSWER` flag to the message, we see the message has only the `FLAGGED` flag.

I do not understand how that happens....

I tried to implement the optimistic concurrent control for the update flag, but either the `.updateDocument` API of Lucene suck as it just returns void (no way to know if the update succeeds or not so we can retry) or the `IndexReader` is not reliable to get the latest status of the document.

**Comment by chibenwa** [comment]
Ok I see. This is because we read the document from Lucene, patch it, then upload it again.

It is very possible for the document not to be updated internally yet (because index changes are async) and thus not seen when updating the document a second time...

**Comment by chibenwa** [comment]
Nuke option: read again from the DB :smiling_imp:

Smart option: see how partial document update had been implemented in OpenSearch / friends. They likely solved the problem already...

**Comment by chibenwa** [comment]
Otherwize I think adding some awaits in the tests might be ok, we thus would aknowlege there is a data race in our Lucene code...

**Comment by quantranhong1999** [comment]
> Otherwize I think adding some awaits in the tests might be ok, we thus would aknowlege there is a data race in our Lucene code...

I added some AWAIT 10 seconds in the MPT test but it did not solve the issue.

> It is very possible for the document not to be updated internally yet (because index changes are async) and thus not seen when updating the document a second time...

Likely not as during debugging I stop for a long time and after that, the update is still not reflected.
Of course with a new `IndexReader` opened (snapshot of current index).

**Comment by quantranhong1999** [comment]
I tried to put AWAIT after every STORE +FLAG command -> not work.

I tried to use the [Luke](https://github.com/DmitryKey/luke) tool to introspect the index during debugging, but not work as we can only check the index after the test...

Likely I would put this work in the standby mode for now. Unless anyone wants to have fun with it...

**Comment by Arsnael** [comment]
How about disabling the mpt tests for now, then continue the migration towards 9.11 to see if this has been done differently or solved on lucene side after?

**Comment by Arsnael** [comment]
It was just a suggestion. This task aint a priority at all, just a nice plus if we can deal with it.

Dont hesitate to take a break on something else :)

**Pull request closed without merging**
