### PR TITLE
JAMES-2586 Avoid sorting PG messages

### PR DESCRIPTION
**Pull request by vttranlina**
The clone pr of https://github.com/apache/james-project/pull/1964
for see the ci test

already:
- rebased master
- squash fixup

### CODE REVIEW

**Comment by Arsnael** [comment]
Last build was hanging forever, in imap mtp search tests, exactly like what I encountered last week here https://github.com/apache/james-project/pull/2048 which seems has been fixed since (it's trying to optimize around that part of the code too)

We had a green build finally on that other PR, I would propose to rebase on that work and see if this modification is still necessary or not?

**Comment by vttranlina** [comment]
yes, please rebase and rerun the ci

**Comment by Arsnael** [comment]
Still the same, should fix this commit

**Review by Arsnael — APPROVED** [review]
Thanks for taking an other look @vttranlina

**Review by quantranhong1999 — APPROVED** [review]

**Comment by Arsnael** [comment]
Please rebase

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
