### PR TITLE
JAMES-2338 quick-start - Typo

### PR DESCRIPTION
**Pull request by provirus**

### CODE REVIEW

**Comment by chibenwa** [comment]
Hi,

This pull request has just been merged.

Thank you again for your dedication toward the James project. If you need help, want to [contribute](https://issues.apache.org/jira/issues/?jql=project%20%3D%20JAMES%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20newbie%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC) [documentation](https://issues.apache.org/jira/issues/?jql=project%20%3D%20JAMES%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20documentation%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC), new [features](https://issues.apache.org/jira/issues/?jql=project%20%3D%20JAMES%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20feature%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC), tests or [bugfix](https://issues.apache.org/jira/issues/?jql=project%20%3D%20JAMES%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20easyfix%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC), please don't hesitate to reach us.

One very last thing: I don't have write access to this repository, hence I can not close this issue. Wouldn't you mind doing it for me? It would avoid me annoying the Apache INFRA team with such simple concerns.

Thanks again,

Cheers,

Benoit

**Comment by provirus** [comment]
thanks

**Comment by provirus** [comment]
It is saying: "Closed with unmerged commits"

**Comment by chibenwa** [comment]
It is normal as your PR was not up to date with the master branch. Futhermore I proceeded with a double rebase (so without merge commits) which tricks github.

However your commit is on the Apache master branch cf : https://github.com/apache/james-project/commits/master?after=b0cb406c8d00d7e63e44d98e734624c35f14c757+34

Cheers,

**Comment by provirus** [comment]
great thanks

**Pull request closed without merging**
