### PR TITLE
JAMES-2586 Implement PostgresBlobStoreDAO

### PR DESCRIPTION
**Pull request by hungphan227**

### CODE REVIEW

**Comment by hungphan227** [comment]
```
    @ParameterizedTest(name = "[{index}] {0}")
    @MethodSource("blobs")
    default void concurrentSaveInputStreamShouldReturnConsistentValues(String description, byte[] bytes) throws ExecutionException, InterruptedException {
        Mono.from(testee().save(TEST_BUCKET_NAME, TEST_BLOB_ID, bytes)).block();
        ConcurrentTestRunner.builder()
            .randomlyDistributedReactorOperations(
                (threadNumber, step) -> testee().save(TEST_BUCKET_NAME, TEST_BLOB_ID, new ByteArrayInputStream(bytes)),
                (threadNumber, step) -> checkConcurrentSaveOperation(bytes)
            )
            .threadCount(10)
            .operationCount(20)
            .runSuccessfullyWithin(Duration.ofMinutes(2));
    }
```

this test failed because it took PostgresBlobStoreDAO 5 mins to complete. Is this acceptable?

**Comment by vttranlina** [comment]
> this test (in ReadSaveBlobStoreDAOContract) failed because it took PostgresBlobStoreDAO 5 mins to complete. Is this acceptable?

It looks un-normal, the "BIG" blob has 12MB, I don't think it takes 5 minutes for that

**Comment by vttranlina** [comment]
caught it, 
`PostgresBlobStoreDAO` using default `postgresExecutor` (single `Connection`) -> We can not insert parallel blob data with a "single" connection.

**First my idea:**
- Using a "pool" connection to replace a "single" connection. I tried to pool with size = 50, It takes ~ 30 sec to complete. (at least it is faster than a few minutes)
(Note that: the Cassandra test needs 10 sec, and S3 needs 3 sec to complete)

**Second idea:**  
- I'm thinking of chunk upload or optimizing somewhere in the Postgresql configuration. (Not sure it is possible, need to research)

**Comment by quantranhong1999** [comment]
FYI, by default (in that test), Cassandra just uses 1 connection to 1 node:
https://docs.datastax.com/en/developer/java-driver/4.10/manual/core/pooling/#configuration

Any chance Postgres locks the row during the insert? I see that the concurrent test trying the insert the blob to the same primary key `TEST_BUCKET_NAME +  TEST_BLOB_ID`. 
Maybe we can try to insert different BlobId(s).

**Comment by vttranlina** [comment]
> FYI, by default (in that test), Cassandra just uses 1 connection to 1 node:

I remember @chibenwa  said that Cassandra, 1 connection, but "pool/ multi/ parallel" inside. 

> Maybe we can try to insert different BlobId(s).

I tried it first, but no different

> I do not think we override the same blobId in the real world BTW.

+1

**Comment by quantranhong1999** [comment]
> I tried it first, but no different

Any chance Postgres locks the whole table while inserting the blob then? Otherwise, maybe it is actually the Postgres connection limit: only allow uploading 1 blob once.

**Comment by chibenwa** [comment]
Pooling connections is a good idea anyway.

Something like 1 core -> one connection would seem like a good design to me.

**Comment by vttranlina** [comment]
> Any chance Postgres locks the whole table while inserting the blob then?

For sure, I tried to remove the Index for the blob_storage table,
But the result is not different (still takes 5 minutes)

**Comment by vttranlina** [comment]
I created a new pr (continue on it) https://github.com/apache/james-project/pull/1883

**Comment by vttranlina** [comment]
we can close it

**Comment by chibenwa** [comment]
I want you @vttranlina to create a ticket on connection pooling first ;-)

**Comment by vttranlina** [comment]
> I want you @vttranlina to create a ticket on connection pooling first ;-)

yes, ticket for it https://github.com/linagora/james-project/issues/5020

**Pull request closed without merging**
