### PR TITLE
JAMES-3497 Upgrade camel to latest version

### PR DESCRIPTION
**Pull request by chibenwa**
Most notably the 3.x release line claims shorter boot time.

I did not try to leverage dependency reductions.

### CODE REVIEW

**Comment by Arsnael** [comment]
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-321/1/testReport/junit/org.apache.james.app.spring/?cloudbees-analytics-link=scm-reporting%2Ftests%2Ffailed

Seems creating issues with Spring tests

**Review by mbaechler — APPROVED** [review]
It looks good

**Comment by chibenwa** [comment]
To be faily honnest @mbaechler as Camel goal is easing integration, but it a James implementation detail, I wonder if we can drop it, and rewritte the logic in pure Java, gaining boot time as well as potential gains for mailet container...

**Comment by mbaechler** [comment]
That's clearly another topic. I would like to write a spec for a new way of building pipeline (including changing Matcher/Mailet) now that I know that part of James well enough.
We could set up a workshop on that topic if you have similar goals.

**Comment by chibenwa** [comment]
> That's clearly another topic.

Agree, it just makes me think of it.

>  I would like to write a spec for a new way of building pipeline (including changing Matcher/Mailet) now that I know that part of James well enough.

Mixing technical and functional changes... One could be carried over without the over one.

BTW having a plain java mailetcontainer would allow to have reactive mailet/matchers easily.

> I would like to write a spec for a new way of building pipeline

To be honnest you make me curious. :-)

> We could set up a workshop on that topic if you have similar goals.

For me the goal could be to enable writing reactive mailet/matchers.

I think that functionnally mailet/matcher are flexible and a real asset of the James project (but I should not be too close minded AND we could leverage modularization to conciliate diverging point of view. Like ok, you get the feature rich mailetcontainer with advanced configuration and sematic OR you could get the preconfigured one for a basic MDA use case. This reminds me of the Basic/Advanced server discussion.)

**Review by Arsnael — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
