### PR TITLE
JAMES-4034 Fix receival of external badly formated From message

### PR DESCRIPTION
**Pull request by chibenwa**
Dropping some production messages because of this.

Be strict about what we send but relaxed about what we receive.

Would fix this regression:

image

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
Test failing on the CI?

https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2400/1/testReport/junit/org.apache.james.smtp/SmtpIdentityVerificationTest/errorsShouldBeIgnoredWhenUnAuthed_File_/

**Review by quantranhong1999 — COMMENTED** [review]
Read it

**Comment by quantranhong1999** [comment]
cc @Arsnael can you rerun the CI?

**Comment by Arsnael** [comment]
Done

**Review by quantranhong1999 — APPROVED** [review]

**Pull request merged**
