### PR TITLE
[NO REVIEW] - CI TEST - rebase Postgresql on master 

### PR DESCRIPTION
**Pull request by vttranlina**
fo ci test
- rebased on master
- Resolve conflict
- FIx checkStyle and compile error: https://github.com/apache/james-project/pull/2312/commits/aa04e09b923e1fc21537a5e349794a891df2583b

Include commits are waiting to merge:
- https://github.com/apache/james-project/pull/2308
- https://github.com/apache/james-project/pull/2287

### CODE REVIEW

**Comment by Arsnael** [comment]
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2312/1/

I find that slightly suspicious... can we check?

**Comment by vttranlina** [comment]
> https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2312/1/
> 
> I find that slightly suspicious... can we check?

It related to pr https://github.com/apache/james-project/pull/2259/files

we added new test cases for postgresql
but it was not passed for cassandra
Can we mark it `unstable` now for postgresql?

**Comment by vttranlina** [comment]
> Can we mark it unstable now for postgresql?

it should mark "Disabled"
I see another test cases was marked also (related to flags concurrency )

ex: https://github.com/apache/james-project/blob/c4367d3952c19bb173468101c7263f26aa8a80ef/mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperRelaxedConsistencyTest.java#L92

**Comment by Arsnael** [comment]
Ok with that, thanks for investigating

**Comment by Arsnael** [comment]
Necessary prior work has been merged btw :)

**Comment by vttranlina** [comment]
> Necessary prior work has been merged btw :)

rebased

**Comment by vttranlina** [comment]
Can you re-run ci @Arsnael A
The failed test on ci is passed on my local

**Comment by Arsnael** [comment]
@vttranlina honestly it's taking long and I start to think I would prefer switching back on making this work with just building postgresql modules, so we can rebase and that it stops being a blocker for the postgres doc (that does not need a build honestly).

I would suggest to check the all build works on a parallel PR. Would you be ok with this?

**Comment by vttranlina** [comment]
it done

**Pull request closed without merging**
