### PR TITLE
Explicit commit after running reindex

### PR DESCRIPTION
**Pull request by woj-tek**
As per mailinglist:

>>    should we finish the operation with the explicit "commit" operation?
> +1
> 
> We could add a `postReindexing()` method for search indexes which commits for Lucene and noop for Opensearch + scanning.
> 
> Then calling it in reindexing task would be a no brainer.
> 
> Do you think you can contribute this?--
> 
> Best regards,
> 
> Benoit TELLIER

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
Seen those tests failing twice in a row. related?

https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2381/4/testReport/

**Comment by chibenwa** [comment]
> do I remember correctly and such improvement could be considered?

+1

Though the CI tests needs to be as extensive as possible.

**Review by chibenwa — APPROVED** [review]
(as always I hate mocks ^^ )

+1

**Comment by chibenwa** [comment]
Yet more mocks

To be fair those are used as last resorts. Generally we favor asserting the actual outcome, which is more resilient to change.

Here it is likely that spawning a full search index was deemed unnecessary and too expensive hence mocked used.

**Comment by chibenwa** [comment]
> Of course, it's better to rely on (correct) outcome but if it could catch spurious calls then I'd say it's beneficial as well :)

Agreed.

(To a similar end, instrumenting the Cassandra driver to programaticaly intercept CQL calls was valuable and contributed to limit count of mocks.)

**Comment by Arsnael** [comment]
Likely unrelated this time indeed, I restarted a build

**Comment by chibenwa** [comment]
> Are the builds / surefire "fail fast", i.e. they stop the run on the first module with failing tests?

Yes

**Pull request merged**
