### PR TITLE
JAMES-3379 Support header:Name:all syntax

### PR DESCRIPTION
**Pull request by chibenwa**
Also supports typing header:Name:asType:all syntax

See related issue: https://github.com/iNPUTmice/jmap/issues/77

See long unhandled issue tracking this on the Linagora backlog: https://github.com/linagora/james-project/issues/3739

That's a quick evening contribution eventually solving some enduser related issues.

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by thoangtd** [comment]
I'm using james server version 3.7.3.
pls, fix this issue in branch 3.7.3

**Comment by chibenwa** [comment]
Hello @thoangtd 

You are very welcome to backport the fix on 3.7.3 :-)

Best regards,

Benoit TELLIER

**Comment by thoangtd** [comment]
Method "Email/query" had set "calculateTotal": true in query but the response from the server is missing "total":
Query: `{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "8a64f89eb617c9b8d0d192888ed0d7de97908e95a9f48ebac60fef71493a43a1",
                
                "filter": {
                    "inMailbox": "a2f75b50-6650-11ed-a669-e5131515e0a2"
                },
                "sort": [
                    {
                        "isAscending": false,
                        "property": "receivedAt"
                    }
                ],
                "collapseThreads": true,
                "calculateTotal": true,
                "position": 0,
                "limit": 30
            },
            "0"
        ]
    ]
}`

Response: 
`{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "Email/query",
            {
                "accountId": "8a64f89eb617c9b8d0d192888ed0d7de97908e95a9f48ebac60fef71493a43a1",
                "queryState": "79f3e366",
                "canCalculateChanges": false,
                "ids": [
                    "af63f590-8b7d-11ed-868a-438f62fd4514",
                    "4440d450-8b4f-11ed-868a-438f62fd4514",
                    "55caba60-8b4f-11ed-868a-438f62fd4514",
                    "17f66d60-8b4a-11ed-868a-438f62fd4514"
                ],
                "position": 0
            },
            "0"
        ]
    ]
}`

**Comment by chibenwa** [comment]
Known: https://issues.apache.org/jira/browse/JAMES-1883

That's more complicated than it seems but contributions would be welcome.

**Won't be fixed here**.

I can offer support on implementing this if you really need it.

**Comment by thoangtd** [comment]
Thanks @chibenwa for support,
 I need to support pagination when user query email with filter, look like 
[
image
](url)

**Comment by chibenwa** [comment]
@thoangtd can we discuss by email of your use case?

My email: btellier@linagora.com

**Comment by chibenwa** [comment]
Merging this work to master for now.

**Pull request merged**
