### PR TITLE
documenting mock smtp server http endpoints

### PR DESCRIPTION
**Pull request by grault**
As per discussion on https://github.com/apache/james-project/pull/715, here are some example sessions for the mock smtp http endpoints, as documentation.

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]
Thanks a lot!

**Comment by grault** [comment]
It's not urgent at all, just wondering, what's an eta for the linagora/mock-smtp-server:latest image having the new endpoints?

**Comment by chibenwa** [comment]
> It's not urgent at all, just wondering, what's an eta for the linagora/mock-smtp-server:latest image having the new endpoints?

So far we do not plan on adding new modules to it as it satisfies (most) of our testing needs.

A couple of months ago I tried to have some codes for SartTls/SSL preference testing but that did not got anywhere.

Would you need specific things ? Feels free to contribute them ;-)

**Comment by grault** [comment]
> Would you need specific things ?

Just the new endpoints you merged in the previous PR, documented in this PR. Currently when I do
```bash
$ docker run --rm -p 25:25 -p 8000:8000 linagora/mock-smtp-server
Unable to find image 'linagora/mock-smtp-server:latest' locally
latest: Pulling from linagora/mock-smtp-server
...
```
Then the `smtpMailsCount` endpoint returns 404.

Do you have plans to roll a new image out?

**Comment by chibenwa** [comment]
> Do you have plans to roll a new image out?

:+1: will do tomorrow

**Comment by chibenwa** [comment]
CF linagora/mock-smtp-server:0.5

**Comment by grault** [comment]
> CF linagora/mock-smtp-server:0.5

Awesomeness, thank you for this.

**Pull request merged**
