### PR TITLE
JAMES-1994 Improve the DEMO

### PR DESCRIPTION
**Pull request by chibenwa**
- Use SSL ports
 - Specify domain parts in the username
 - link more advanced tutorials
 - Have a step by step thunderbird settup with screenshots

### CODE REVIEW

**Comment by fnwirth** [comment]
When using james-cli a warning is outputet that SLF4J classes can't be loaded. This could be mentioned in the tutorial

**Comment by chibenwa** [comment]
Or... This could be fixed! 

I'll check tomorrow, likely addressed by the 3.7.0 release line...

**Comment by chibenwa** [comment]
```
docker run -d apache/james:memory-latest
...
$ docker exec -ti  2db5b4f2694619f2e94efbb38101548488d3ed839eedb277da2a1396deb16d42 james-cli ListDomains
localhost
ListDomains command executed sucessfully in 251 ms.
```

This issue is still present with the 3.7.0 release line but apparently only for the JPA image.

```
$ docker run -d apache/james:jpa-latest
...
$ docker exec -ti 452d2fe3f6281d78aeb8d321eee00510f8caa51fe75fc62f5542bc67b82d91f0 james-cli ListDomains
12:01:19,363 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
12:01:19,365 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
12:01:19,366 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/root/resources/logback.xml]
12:01:19,458 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
12:01:19,460 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [ch.qos.logback.classic.jul.LevelChangePropagator] to the object stack
12:01:19,481 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@77f1baf5 - Propagating DEBUG level on Logger[ROOT] onto the JUL framework
12:01:19,482 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
12:01:19,482 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
12:01:19,484 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
12:01:19,485 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:01:19,488 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@41a2befb - As of version 1.2.0 "immediateFlush" property should be set within the enclosing Appender.
12:01:19,488 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@41a2befb - Please move "immediateFlush" property into the enclosing appender.
12:01:19,535 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@41a2befb - Setting the "immediateFlush" property of the enclosing appender to false
12:01:19,535 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
12:01:19,535 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@77f1baf5 - Propagating WARN level on Logger[ROOT] onto the JUL framework
12:01:19,535 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
12:01:19,536 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.james] to INFO
12:01:19,536 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@77f1baf5 - Propagating INFO level on Logger[org.apache.james] onto the JUL framework
12:01:19,536 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
12:01:19,538 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6c40365c - Registering current configuration as safe fallback point

localhost
ListDomains command executed sucessfully in 254 ms.
```

Well, it loads. I guess we need to review the logback settings to get it a bit less verbose.... (Hunt the logback.xml resource on the classpath!)

**Comment by fnwirth** [comment]
It says here [http://www.slf4j.org/codes.html#StaticLoggerBinder](url): "Placing one (and only one) of slf4j-nop.jar slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar or logback-classic.jar on the class path should solve the problem". Is it possible that several of these files are on the class path?

**Comment by chibenwa** [comment]
```
$ docker run -d apache/james:jpa-latest
...
$ docker exec -ti 59f6f7d20f29f67d6b5efdea424954f855960b37d6012d55860f294e7a7bc34a james-cli ListDomains
localhost
ListDomains command executed sucessfully in 270 ms.
```

(Thanks for the report)

**Comment by fnwirth** [comment]
I just understood the following about our discussion with sending e-mail in the demo: I was refering to [this](https://james.staged.apache.org/james-project/3.7.0/servers/5-minute-demo.html) tutorial, which makes use of the image _apache/james:demo-3.6.0_. I was not able to send e-mails with this container.

I now understand that you are refering to the image _linagora/james-jpa-guice:latest_. As described by you, I was out of the box able to send e-mails with this container.

**Comment by chibenwa** [comment]
> I was not able to send e-mails with this container.

To send email to who?

> I now understand that you are refering to the image linagora/james-jpa-guice:latest.

demo is just a provisionned JPA image.

**Comment by fnwirth** [comment]
> 
> 
> > I was not able to send e-mails with this container.
> 
> To send email to who?
To the user theirselves (the same user I can access the IMAP folder)

**Pull request merged**
