### PR TITLE
Upgrade elasticsearch. And bump camel.

### PR DESCRIPTION
**Pull request by lmilev**
Upgrade elasticsearch libraries.
2.2.1 is rolling upgrade compatible with 2.4.6

Camel 2.19.1 to 2.19.4 contains dozens of bug fixes and stability improvements. 

Resources:
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/setup-upgrade.html
https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12341575&projectId=12311211

### CODE REVIEW

**Comment by rouazana** [comment]
can you try to cleanup your commit history please? You should basically have only 2 commits: one for caml upgrade, one for elasticsearch upgrade.

**Comment by lmilev** [comment]
Thank you for taking a look, and the tip for rebase!

I created a new clean pull request here:
https://github.com/apache/james-project/pull/100

**Comment by lmilev** [comment]
Also, I separated the Camel upgrade into a separate pull request just-in-case here:

https://github.com/apache/james-project/pull/101

**Comment by chibenwa** [comment]
Hi @lmilev 

As this PR was splitted in two, we can consider closing this PR.

I don't have write access to this repository, hence I can not close this issue. Wouldn't you mind doing it for me? It would avoid me annoying the Apache INFRA team with such simple concerns.

Cheers,

Benoit Tellier

**Comment by ieugen** [comment]
Hello @lmilev , Thanks for the contribution.
Sorry for not getting this merged sooner. 
It seems that now it is too late since the updates have been made.
I'm going to close this PR since there is nothing more to do.

We'll be more swift in getting things merged in the future.

**Pull request closed without merging**
