### PR TITLE
JAMES-3752 Allow disabling ImapChannelUpstreamHandler heartbeat handler

### PR DESCRIPTION
**Pull request by vttranlina**
Jira: https://issues.apache.org/jira/browse/JAMES-3752

### CODE REVIEW

**Review by chibenwa — COMMENTED** [review]
Documentation in server/apps/distributed-app/docs ?

**Comment by vttranlina** [comment]
> Documentation in server/apps/distributed-app/docs ?

yes, it's already in pr
`server/apps/distributed-app/docs/modules/ROOT/pages/configure/imap.adoc`

**Review by chibenwa — APPROVED** [review]

**Comment by chibenwa** [comment]
Rebase please :-P

**Review by Arsnael — APPROVED** [review]

**Comment by vttranlina** [comment]
Rebase master

**Review by chibenwa — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by vttranlina** [comment]
Rebase master

**Pull request merged**
