### PR TITLE
Remove GroupMembershipResolver and implement

### PR DESCRIPTION
**Pull request by vttranlina**
I propose to remove `GroupMembershipResolver`, `SimpleGroupMembershipResolver` and related

## Reason: 
- interface GroupMembershipResolver has only one implement is SimpleGroupMembershipResolver
- As the author's comment at `SimpleGroupMembershipResolver`:
```
There is no persistence. You will get only what you add
```
And nowhere in James call to `.addMemberShip` method => `.isMember` always return FALSE

Remove the exuberancy code to make it simpler.

### CODE REVIEW

**Comment by chibenwa** [comment]
Please create an associated JIRA

**Comment by chibenwa** [comment]
After looking at the changeset, I see that there is an interface and there is tests regarding group resolution in the face of a group.

Mailbox, for some people is a bit more than a sub-part object but an attempt to build a generic email storage reference.

As such I fear some might rely on group resolution in customized James instances or might use this part of the `mailbox-api` in there project.

I do support your initiaiive: ACL part of the code is complex. Yet I believe we should raise the topic on server-dev mailing list too... Can you send a mail on that very topic?

Regards,

Benoit

**Comment by chibenwa** [comment]
Reading the code,  `MailboxACLResolver` is an interface. People having custom stuff would then be able to backport their changes behind it. THis makes your change less critical.

But let's send the mail anyway ;-)

**Comment by vttranlina** [comment]
> But let's send the mail anyway ;-)

Yes, I sent it. 
https://www.mail-archive.com/server-dev@james.apache.org/msg71095.html

**Pull request merged**
