### PR TITLE
JAMES-3214 Add missing test scope

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
 % du -h -d 1 server/container/guice/jpa-guice/target/james-server-jpa-guice.lib/
94M     server/container/guice/jpa-guice/target/james-server-jpa-guice.lib/
```

**Comment by ieugen** [comment]
I've made some updates to the project. 
I've separated the cli from the server. The cli has 30MB of libs. 

james-server size is as expected. 

Since we are running on java 11, we could drop the scala 8 compat. 
```
ls -lSh james-cli/build/distributions/james-cli/lib/
total 30M
-rw-r--r-- 1 ieugen ieugen  13M iun 12 13:19 icu4j-64.2.jar
-rw-r--r-- 1 ieugen ieugen 5,5M iun 12 13:19 scala-library-2.13.1.jar
-rw-r--r-- 1 ieugen ieugen 2,7M mai  3 06:17 guava-25.1-jre.jar
-rw-r--r-- 1 ieugen ieugen 1,5M iun 12 13:19 reactor-core-3.3.0.RELEASE.jar
-rw-r--r-- 1 ieugen ieugen 1,3M feb 17 21:29 jackson-databind-2.9.9.jar
-rw-r--r-- 1 ieugen ieugen 718K iun 12 13:19 javassist-3.21.0-GA.jar
-rw-r--r-- 1 ieugen ieugen 644K mai  3 05:45 javax.mail-1.6.2.jar
-rw-r--r-- 1 ieugen ieugen 626K iun 12 13:19 scala-java8-compat_2.13-0.9.0.jar
-rw-r--r-- 1 ieugen ieugen 618K iun 12 13:19 commons-configuration2-2.5.jar
-rw-r--r-- 1 ieugen ieugen 493K feb 17 21:24 commons-lang3-3.9.jar
-rw-r--r-- 1 ieugen ieugen 388K iun 12 13:19 fst-2.57.jar
-rw-r--r-- 1 ieugen ieugen 336K mai  3 06:17 checker-qual-2.0.0.jar
-rw-r--r-- 1 ieugen ieugen 323K mai  3 05:45 apache-mime4j-dom-0.8.3.jar
-rw-r--r-- 1 ieugen ieugen 318K feb 17 21:29 jackson-core-2.9.9.jar
-rw-r--r-- 1 ieugen ieugen 267K iun 12 13:19 apache-james-mailbox-api-3.5.0-SNAPSHOT.jar
-rw-r--r-- 1 ieugen ieugen 210K feb 17 21:33 commons-io-2.6.jar
-rw-r--r-- 1 ieugen ieugen 201K iun 12 13:19 commons-text-1.7.jar
-rw-r--r-- 1 ieugen ieugen 169K iun 12 13:19 james-server-util-3.5.0-SNAPSHOT.jar
-rw-r--r-- 1 ieugen ieugen 121K iun 12 13:19 throwing-lambdas-0.5.0.jar
-rw-r--r-- 1 ieugen ieugen 102K mai  3 05:45 apache-mime4j-core-0.8.3.jar
-rw-r--r-- 1 ieugen ieugen  88K iun 12 13:19 james-server-data-api-3.5.0-SNAPSHOT.jar
-rw-r--r-- 1 ieugen ieugen  77K feb 17 21:33 javax.activation-1.2.0.jar
-rw-r--r-- 1 ieugen ieugen  65K feb 17 21:24 jackson-annotations-2.9.0.jar
-rw-r--r-- 1 ieugen ieugen  54K iun 15 18:31 objenesis-2.5.1.jar
-rw-r--r-- 1 ieugen ieugen  53K feb 17 21:35 commons-cli-1.4.jar
-rw-r--r-- 1 ieugen ieugen  52K iun 12 13:19 apache-mailet-api-3.5.0-SNAPSHOT.jar
-rw-r--r-- 1 ieugen ieugen  48K iun 12 13:19 james-core-3.5.0-SNAPSHOT.jar
-rw-r--r-- 1 ieugen ieugen  41K iun 12 13:19 slf4j-api-1.7.27.jar
-rw-r--r-- 1 ieugen ieugen  35K iun 12 13:19 james-server-cli-3.5.0-SNAPSHOT.jar
-rw-r--r-- 1 ieugen ieugen  31K iun 12 13:19 james-server-task-api-3.5.0-SNAPSHOT.jar
-rw-r--r-- 1 ieugen ieugen  26K feb 17 21:29 javax.annotation-api-1.3.2.jar
-rw-r--r-- 1 ieugen ieugen  24K iun 12 13:19 james-server-mailbox-jmx-3.5.0-SNAPSHOT.jar
-rw-r--r-- 1 ieugen ieugen  20K feb 17 21:24 jsr305-3.0.2.jar
-rw-r--r-- 1 ieugen ieugen  16K iun 12 13:19 james-server-mailrepository-api-3.5.0-SNAPSHOT.jar
-rw-r--r-- 1 ieugen ieugen  14K feb 17 21:33 error_prone_annotations-2.1.3.jar
-rw-r--r-- 1 ieugen ieugen  13K iun 12 13:19 guavate-1.0.0.jar
-rw-r--r-- 1 ieugen ieugen  12K feb 17 21:24 reactive-streams-1.0.3.jar
-rw-r--r-- 1 ieugen ieugen 8,6K feb 17 21:24 j2objc-annotations-1.1.jar
-rw-r--r-- 1 ieugen ieugen 3,5K feb 17 21:33 animal-sniffer-annotations-1.14.jar
-rw-r--r-- 1 ieugen ieugen 2,5K feb 17 21:28 javax.inject-1.jar
-rw-r--r-- 1 ieugen ieugen  261 iun 15 21:46 james-cli.jar
```


./gradlew :james-cli:dependencies 
```
untimeClasspath - Runtime classpath of source set 'main'.
\--- org.apache.james:james-server-cli:3.5.0-SNAPSHOT
     +--- org.apache.james:james-server-data-api:3.5.0-SNAPSHOT
     |    +--- org.apache.james:james-core:3.5.0-SNAPSHOT
     |    |    +--- com.github.fge:throwing-lambdas:0.5.0
     |    |    +--- com.github.steveash.guavate:guavate:1.0.0
     |    |    |    +--- com.google.guava:guava:19.0 -> 25.1-jre
     |    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
     |    |    |    |    +--- org.checkerframework:checker-qual:2.0.0
     |    |    |    |    +--- com.google.errorprone:error_prone_annotations:2.1.3
     |    |    |    |    +--- com.google.j2objc:j2objc-annotations:1.1
     |    |    |    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
     |    |    |    \--- org.apache.commons:commons-lang3:3.4 -> 3.9
     |    |    +--- com.google.guava:guava:25.1-jre (*)
     |    |    +--- com.sun.activation:javax.activation:1.2.0
     |    |    +--- com.sun.mail:javax.mail:1.6.2
     |    |    +--- commons-io:commons-io:2.6
     |    |    \--- org.slf4j:slf4j-api:1.7.27
     |    +--- org.apache.james:james-server-mailrepository-api:3.5.0-SNAPSHOT
     |    |    \--- org.apache.james:apache-mailet-api:3.5.0-SNAPSHOT
     |    |         +--- org.apache.james:apache-james-mailbox-api:3.5.0-SNAPSHOT
     |    |         |    +--- org.apache.james:james-core:3.5.0-SNAPSHOT (*)
     |    |         |    +--- org.apache.james:james-server-task-api:3.5.0-SNAPSHOT
     |    |         |    |    +--- com.google.guava:guava:25.1-jre (*)
     |    |         |    |    +--- javax.annotation:javax.annotation-api:1.3.2
     |    |         |    |    +--- org.scala-lang:scala-library:2.13.1
     |    |         |    |    +--- org.scala-lang.modules:scala-java8-compat_2.13:0.9.0
     |    |         |    |    |    \--- org.scala-lang:scala-library:2.13.0 -> 2.13.1
     |    |         |    |    \--- org.slf4j:slf4j-api:1.7.27
     |    |         |    +--- org.apache.james:apache-mime4j-dom:0.8.3
     |    |         |    |    \--- org.apache.james:apache-mime4j-core:0.8.3
     |    |         |    +--- com.github.fge:throwing-lambdas:0.5.0
     |    |         |    +--- com.github.steveash.guavate:guavate:1.0.0 (*)
     |    |         |    +--- com.google.guava:guava:25.1-jre (*)
     |    |         |    +--- com.ibm.icu:icu4j:64.2
     |    |         |    +--- com.sun.mail:javax.mail:1.6.2
     |    |         |    +--- javax.inject:javax.inject:1
     |    |         |    +--- org.apache.commons:commons-lang3:3.9
     |    |         |    +--- org.apache.commons:commons-text:1.7
     |    |         |    |    \--- org.apache.commons:commons-lang3:3.9
     |    |         |    \--- org.slf4j:slf4j-api:1.7.27
     |    |         +--- org.apache.james:james-core:3.5.0-SNAPSHOT (*)
     |    |         +--- org.apache.james:james-server-util:3.5.0-SNAPSHOT
     |    |         |    +--- org.apache.james:apache-mime4j-dom:0.8.3 (*)
     |    |         |    +--- com.github.fge:throwing-lambdas:0.5.0
     |    |         |    +--- com.github.steveash.guavate:guavate:1.0.0 (*)
     |    |         |    +--- com.google.guava:guava:25.1-jre (*)
     |    |         |    +--- com.ibm.icu:icu4j:64.2
     |    |         |    +--- com.sun.mail:javax.mail:1.6.2
     |    |         |    +--- commons-io:commons-io:2.6
     |    |         |    +--- io.projectreactor:reactor-core:3.3.0.RELEASE
     |    |         |    |    \--- org.reactivestreams:reactive-streams:1.0.3
     |    |         |    +--- javax.inject:javax.inject:1
     |    |         |    +--- org.apache.commons:commons-lang3:3.9
     |    |         |    \--- org.slf4j:slf4j-api:1.7.27
     |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.9.9
     |    |         |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
     |    |         |    \--- com.fasterxml.jackson.core:jackson-core:2.9.9
     |    |         +--- com.github.steveash.guavate:guavate:1.0.0 (*)
     |    |         +--- com.google.guava:guava:25.1-jre (*)
     |    |         +--- com.sun.mail:javax.mail:1.6.2
     |    |         +--- de.ruedigermoeller:fst:2.57
     |    |         |    +--- com.fasterxml.jackson.core:jackson-core:2.8.8 -> 2.9.9
     |    |         |    +--- org.javassist:javassist:3.21.0-GA
     |    |         |    \--- org.objenesis:objenesis:2.5.1
     |    |         \--- org.slf4j:slf4j-api:1.7.27
     |    +--- org.apache.commons:commons-configuration2:2.5
     |    |    +--- org.apache.commons:commons-lang3:3.9
     |    |    \--- org.apache.commons:commons-text:1.6 -> 1.7 (*)
     |    +--- com.google.guava:guava:25.1-jre (*)
     |    \--- com.sun.mail:javax.mail:1.6.2
     +--- org.apache.james:james-server-mailbox-jmx:3.5.0-SNAPSHOT
     |    +--- org.apache.james:apache-james-mailbox-api:3.5.0-SNAPSHOT (*)
     |    +--- org.apache.james:james-server-util:3.5.0-SNAPSHOT (*)
     |    \--- org.slf4j:slf4j-api:1.7.27
     +--- org.apache.james:james-server-util:3.5.0-SNAPSHOT (*)
     +--- com.google.guava:guava:25.1-jre (*)
     \--- commons-cli:commons-cli:1.4

```

**Comment by chibenwa** [comment]
> Since we are running on java 11, we could drop the scala 8 compat.

:+1: let's add a separate PR, as this is less linked to an obvious mistake.

> I've separated the cli from the server. The cli has 30MB of libs.

Well my thought is: "the CLI should not depend on any server component". However JMX makes this goal hard to achieve.

I wonder if we can't create `/server/container/jmx-mbeans` + `/server/container/jmx-mbeans-impl` projects, `/server/container/jmx-mbeans` being 0 dependencies, and  `/server/container/jmx-mbeans-impl`  pulling all the dependencies (but on the server side). However given the middle term plan to migrate the CLI to rely on webadmin, I wonder if this is worth the investment.

We should do a couple of easy dependencies tweaks, however:

 - The dependency between mailbox-api & mailet-api is suspicious.

 - mailbox-api has a dependency to `task-api` only brought by re-indexing, we could relocate that to the *mvn* reindexing maven module.

 - Another sanitary move would be relocating `MailRepositoryStore` (and related classes) in mailrepository-api to not pull the related dependency in `server-data`

**Comment by ieugen** [comment]
Hi, 

We could do lots of work but we should also consider the value we get from it.
Cleaning up dependencies is valuable IMO since it simplifies things.
We get less things to worry about, less things to check. 

For the CLI, things are IMO good enough. 
The JMX split sounds good but is a nice to have IMO. 
If if's simple to do / fast we could work on it.

**Comment by chibenwa** [comment]
Hello @ieugen ,

We should not click merge buttons on Apache repositories in github.

Code source needs to be merged on apache repositoruies, that will then mirror them to Github.

I will try to push changes on the Apache git to see if it solves synchronisation concerns.

Also I got the following error while running tests:

```
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.015 s <<< FAILURE! - in org.apache.james.jmap.rfc8621.distributed.DistributedAuthenticationTest
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR] org.apache.james.jmap.rfc8621.distributed.DistributedAuthenticationTest  Time elapsed: 0.015 s  <<< ERROR!
[d2245f5750b18af22418b148f7adeb6dc1e710e8] java.lang.NoClassDefFoundError: org/apache/james/util/docker/DockerContainer
[d2245f5750b18af22418b148f7adeb6dc1e710e8] 	at org.apache.james.jmap.rfc8621.distributed.DistributedAuthenticationTest.<clinit>(DistributedAuthenticationTest.java:37)
[d2245f5750b18af22418b148f7adeb6dc1e710e8] Caused by: java.lang.ClassNotFoundException: org.apache.james.util.docker.DockerContainer
[d2245f5750b18af22418b148f7adeb6dc1e710e8] 	at org.apache.james.jmap.rfc8621.distributed.DistributedAuthenticationTest.<clinit>(DistributedAuthenticationTest.java:37)
[d2245f5750b18af22418b148f7adeb6dc1e710e8] 
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [INFO] Running org.apache.james.jmap.rfc8621.distributed.DistributedMailboxGetMethodTest
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.apache.james.jmap.rfc8621.distributed.DistributedMailboxGetMethodTest
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR] org.apache.james.jmap.rfc8621.distributed.DistributedMailboxGetMethodTest  Time elapsed: 0 s  <<< ERROR!
[d2245f5750b18af22418b148f7adeb6dc1e710e8] java.lang.NoClassDefFoundError: Could not initialize class org.apache.james.backends.es.DockerElasticSearchSingleton
[d2245f5750b18af22418b148f7adeb6dc1e710e8] 	at org.apache.james.jmap.rfc8621.distributed.DistributedMailboxGetMethodTest.<clinit>(DistributedMailboxGetMethodTest.java:37)
[d2245f5750b18af22418b148f7adeb6dc1e710e8] 
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [INFO] Running org.apache.james.jmap.rfc8621.distributed.DistributedEchoMethodTest
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in org.apache.james.jmap.rfc8621.distributed.DistributedEchoMethodTest
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR] org.apache.james.jmap.rfc8621.distributed.DistributedEchoMethodTest  Time elapsed: 0.001 s  <<< ERROR!
[d2245f5750b18af22418b148f7adeb6dc1e710e8] java.lang.NoClassDefFoundError: Could not initialize class org.apache.james.backends.es.DockerElasticSearchSingleton
[d2245f5750b18af22418b148f7adeb6dc1e710e8] 	at org.apache.james.jmap.rfc8621.distributed.DistributedEchoMethodTest.<clinit>(DistributedEchoMethodTest.java:38)
[d2245f5750b18af22418b148f7adeb6dc1e710e8] 
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [INFO] 
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [INFO] Results:
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [INFO] 
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR] Errors: 
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR]   DistributedAuthenticationTest.<clinit>:37 » NoClassDefFound org/apache/james/u...
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR]   DistributedEchoMethodTest.<clinit>:38 » NoClassDefFound Could not initialize c...
[d2245f5750b18af22418b148f7adeb6dc1e710e8] [ERROR]   DistributedMailboxGetMethodTest.<clinit>:37 » NoClassDefFound Could not initia...
```

Some code relied on the dependency I just 'cut' and it needs to be re-added.

As such, and in order to minimize the inconvenience for other people working on the project, I will revert this change and reopen the relevant pull requests.

Cheers,

Benoit

**Comment by chibenwa** [comment]
Reopened here https://github.com/apache/james-project/pull/210

**Comment by ieugen** [comment]
Thanks for pointing that out and apologies for giving you work and head aches in the morning.

It skipped my mind that github is a mirror. Thanks for reminding me. 
Where can I check if a PR is good or not?
I've seen that James jenkins builds on apache infra are not updated.

https://builds.apache.org/view/All/job/james-project/ 

I also think the development flow is quite complicated: 
- with JIRA
- github PR's
- github issues
- github mirror of apache git 

It's very time consuming for me to keep track of all of these and have confidence that when I merge something it is good enough to merge.
When I close a github issue I have to double check JIRA. 

I think this is something we should address and simplify as well.

**Comment by chibenwa** [comment]
> Thanks for pointing that out and apologies for giving you work and head aches in the morning.

No worries, it was mid-afternoon here ^^

> Where can I check if a PR is good or not?

That's an issue. CI is not setted up on Apache github repository. We do pass a build on linagora CI (we open another PR on our repo so that the CI runs on it, and link it back on the Apache repository).

https://builds.apache.org/view/All/job/james-project/ is outdated.

The above mentioned workflow is based on the assumption that committers are able to run the tests by themselves (understand with their means), but that obviously don't scale very well.

Obviously having Apache builds back is a must have.

> I think this is something we should address and simplify as well.

:+1:

**Pull request merged**
