### PR TITLE
[NO_MERGE] For CI test - update postgresql branch to the latest master

### PR DESCRIPTION
**Pull request by vttranlina**
To update PostgreSQL to the latest master:

Steps:
- Checkout the latest PostgreSQL and rebase interactively on the latest master.
- Resolve any conflicts.
- Adapt PostgreSQL to fix compile code failures.

Green List:
- [x] CI is green on the PostgreSQL module (use the PostgreSQL Jenkinsfile).
- [x] CI is green on all modules.

Note:
- Most conflicts come from the Antora documentation.

### CODE REVIEW

**Comment by vttranlina** [comment]
:green_apple: CI is green on the PostgreSQL module (use the PostgreSQL Jenkinsfile).  :green_apple:

**Comment by vttranlina** [comment]
:green_apple: :green_apple: :green_apple: CI is green on all modules.

**Review by quantranhong1999 — APPROVED** [review]
Great job.

**Comment by Arsnael** [comment]
Good job! 

How do we merge that into postgresql? I guess we push this on postgresql branch minus the commit `[Update Jenkinsfile master (just for ci test)](https://github.com/apache/james-project/pull/2467/commits/50f8b1ddf1d344f811b2785a6dd3af9af6d43f8d)` correct?

**Comment by vttranlina** [comment]
> Good job!
> 
> How do we merge that into postgresql? I guess we push this on postgresql branch minus the commit `[Update Jenkinsfile master (just for ci test)](https://github.com/apache/james-project/pull/2467/commits/50f8b1ddf1d344f811b2785a6dd3af9af6d43f8d)` correct?

absolute correct

**Comment by Arsnael** [comment]
Done, will close this for now. Thanks for the work on this guys!

**Pull request closed without merging**
