### PR TITLE
JAMES-3759 Fix typo and enable leak detector for real

### PR DESCRIPTION
**Pull request by mbaechler**
Co-Authored-By: Jean Helou <jean.helou@gmail.com>

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Comment by vttranlina** [comment]
After fixing the typo, we will get ci fail. 
Maybe it is related https://github.com/apache/james-project/pull/940#issuecomment-1085518526

**Comment by mbaechler** [comment]
> After fixing the typo, we will get ci fail. Maybe it is related [#940 (comment)](https://github.com/apache/james-project/pull/940#issuecomment-1085518526)

Yes, it's why I opened https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3760

**Comment by chibenwa** [comment]
That is a question that I asked on JIRA but I got no answer.

From what it seems, at least on james-core where this build fails, we are mostly testing how tests manages mails, and not really james itself. It's likely long to fix for limited benefits.

How about activating leak detection in only strategically chosen projects like integration tests instead?

**Comment by chibenwa** [comment]
Is there any plan to carry on this work?

**Comment by jeantil** [comment]
That's not to be answered by the authors of the PR I'm afraid. I still think the current situation is bad: 
- the build files contain senseless configuration with typos
- contributors and the CI log warnings in every tests we run because that's the default policy when the detector is left unconfigured

In https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3760 you suggest disabling the leak detector entirely to which I answered that this would prevent early detection of new leaks in production code.
I am not familiar enough with the leak detector code and how it works but would it be possible to have a whitelist of sources for which leaks are ok and then actually fix the problem ?

**Comment by chibenwa** [comment]
Agreed, i'm in favor of fixing the typo and turning off leak detection in tests to not be flooded as we do not achieve good resource management in our tests.

**Comment by chibenwa** [comment]
Well any places that creates a mail is suspicious IMO. Hard to say "that stack is okish, that one's not".

**Comment by chibenwa** [comment]
Early detection is the reason we activated it in tests, but in the middle of the flood we will not notice anything, thus as of today early detection in build seems like a non reached objective to me.

**Pull request closed without merging**
