### PR TITLE
JAMES-2296 JAMES-3689 fix removal by recipient in more cases

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Comment by chibenwa** [comment]
I don't know why no build was started here, it looks like the CI did not find the PR in the first place.

I will try to reopen, to see how it plays out.

**Comment by Arsnael** [comment]
Seems it's building now. Looks like a delay on the CI, go figure^^'

**Comment by chibenwa** [comment]
> Seems it's building now. Looks like a delay on the CI, go figure^^

Not really, I opened another PR, with the exact same SHA1, hence the build is reported here as well. But this very PR is still not to be found by Jenkins :-)

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
