### PR TITLE
JAMES-2828 JDBCMailRepository fails to message into PostgreSQL when per recipient headers are absent

### PR DESCRIPTION
**Pull request by jtconsol**
This fixes the aforementioned problem by going from ` insertMessage.setNull(9, Types.BLOB);` to `insertMessage.setObject(9, null);` - the latter works on PostgreSQL. I've positively tested it on Oracle and MySQL, and it also runs on Derby used in James' tests, so it seems pretty portable. See [this SO answer](https://stackoverflow.com/a/34128743/1529709) for details on PostgreSQL's BLOB handling.

### CODE REVIEW

**Comment by Arsnael** [comment]
I know I approved, but do you think you could write a test or two about that as well? Thanks !

**Comment by jtconsol** [comment]
I'll try to write tests... as with my other PR, if you have any tips on that, send them my way please :)

**Comment by jtconsol** [comment]
@Arsnael Unfortunately, [like I laid out here](https://github.com/apache/james-project/pull/172#issuecomment-546057176), this also can't be tested as such. It is a vendor specific issue and the Derby database used in the tests doesn't exhibit this problem, so it can't catch it.

**Comment by jtconsol** [comment]
Removed XML indentation commit as per [instructions](https://github.com/apache/james-project/pull/172#issuecomment-547806998).

**Pull request closed without merging**
