### PR TITLE
[BUILD] Use git-commit-id-maven-plugin in server/apps only

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by vttranlina — APPROVED** [review]

**Comment by Arsnael** [comment]
Not convinced it will solve our problem down the line, but can try

**Review by quantranhong1999 — APPROVED** [review]

**Comment by Arsnael** [comment]
Or not... I just tested it locally with TMail.

The problem is still here when you try to build, just been moved:

```
[ERROR] Failed to execute goal io.github.git-commit-id:git-commit-id-maven-plugin:7.0.0:revision (get-the-git-infos) on project james-server-cli: Git command exited with invalid status [128]: directory: `/home/rene/Dev/github/tmail-backend/.git/modules`, command: `git describe --always --dirty=-dirty --match=* --abbrev=7`, stdout: ``, stderr: `fatal: this operation must be run in a work tree` -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :james-server-cli
```

**Comment by chibenwa** [comment]
> Not convinced it will solve our problem down the line, but can try

Both are not mutually exclusive, correct?

**Comment by Arsnael** [comment]
> Both are not mutually exclusive, correct?

I mean you can move the plugin to server/apps sure, but upgrading it to the latests version is still blocking our own build as a result.

**Comment by chibenwa** [comment]
So we can still merge this...

We do not have a command line option to diable that plugin in tmail build?

**Comment by Arsnael** [comment]
> We do not have a command line option to diable that plugin in tmail build?

https://github.com/apache/james-project/pull/2049#issuecomment-1963452919

**Comment by jeantil** [comment]
It's should be possible to completely disable the plugin by command line
parameter. I'll try to look it up but as I said limited connectivity

Ideally the plugin should be associated to a profile to be used only for ci
and release of James.


I am hesitant about not including the version in every artifact. For people
pulling snapshots it felt like a useful feature

**Comment by chibenwa** [comment]
You convinced me @jeantil

**Pull request closed without merging**
