### PR TITLE
Jwt-revoker container update for oidc example

### PR DESCRIPTION
**Pull request by Arsnael**
The rpc client from Krakend don't seem to really handle reconnections. It makes more sense as well to open a connection and close it when we finish using it.

### CODE REVIEW

**Comment by chibenwa** [comment]
So, for every request we do open a new connection, right?

Performance wise, this do not look wise! This might be acceptable as "logouts" are expected to be rare, but I would prefer us to just renew connections if they are broken, not all the time.

**Comment by Arsnael** [comment]
> So, for every request we do open a new connection, right?
> 
> Performance wise, this do not look wise! This might be acceptable as "logouts" are expected to be rare, but I would prefer us to just renew connections if they are broken, not all the time.

Honesly the krakend rpc client looks very simple to me, without such mechanisms... but yeah I will try to check... That might imply connection detection, retries, etc... and I'm not proficient in golang just saying

**Comment by Arsnael** [comment]
Ideal would be to have one persistent connection between jwt-revoker and krakend for resources and performances concerns. But that would imply a considerable effort to implement necessary things like a pool of connections, connection loss detection, retry mechanisms, ... in golang

Because logout is considered not happening often, it's totally acceptable for now to only create a connection when adding a token to krakend and then closing it down (which is what the above PR proposes).

**Review by chibenwa — APPROVED** [review]
I think one connection per logout is acceptable, especially in an example folder.

**Pull request merged**
