### PR TITLE
JAMES-1902 Reorganizes and renames queue related guice modules

### PR DESCRIPTION
**Pull request by jeantil**
- groups guice queue bindings in server/container/guice/queue
- extracts memory queue bindings from memory-guice assembly
- renames queue related artifact to drop james-server prefix

related discussion https://www.mail-archive.com/server-dev@james.apache.org/msg68823.html

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Review by mbaechler — APPROVED** [review]
Awesome work, thank you so much

**Review by rouazana — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]
Thanks @jeantil for the nice contribution, I started a build on our CI here : https://github.com/linagora/james-project/pull/4038

**Comment by chibenwa** [comment]
Hello Jean,

I just merged this work, thanks again for it!

Can you close this PR?

We are awaiting for many more maven module reorganisation & renaming ;-)

Cheers,

Benoit

**Comment by jeantil** [comment]
Thanks benoit

**Pull request closed without merging**
