### PR TITLE
JAMES-4040 JMAP mailbox role spam => junk

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by quantranhong1999 — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
CI was down when this work was pushed. rebased on master and repushed to get the CI catch the build

**Comment by Arsnael** [comment]
https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2261/7/#showFailuresLink

Is it related?

**Comment by chibenwa** [comment]
> Is it related?

Yes it was: role is junk and no longer spam. this caused integration tests to break for SPamAssassin...

**Comment by Arsnael** [comment]
Restarted manually as well... if tomorrow still the same I will open a ticket to infra i guess...

**Review by vttranlina — APPROVED** [review]

**Pull request merged**
