### PR TITLE
JAMES-2586 PopulateEmailQueryViewTask should not hang for postgres-app

### PR DESCRIPTION
**Pull request by quantranhong1999**
Root cause: likely a jooq reactive bug. Likely the query that lists a big amount of users somehow blocks the jooq thread.

Mitigate fix: `collectList` to await the list users query to finish before executing other queries...

A similar fix: https://github.com/apache/james-project/commit/03e4b363409adf197ae3af667996b537a69e934f

### CODE REVIEW

**Review by chibenwa — COMMENTED** [review]
Question:

Does adding `.publishOn(Schedulers.parrallel())` in `PG UsersRepository::listReactive` fixes the issue?

**Comment by quantranhong1999** [comment]
> Does adding .publishOn(Schedulers.parrallel()) in PG UsersRepository::listReactive fixes the issue?

It does not.

**Comment by quantranhong1999** [comment]
Rethink about it, I think putting `.collectList` in `PG UsersRepository::listReactive` may be a more common fix.

**Comment by chibenwa** [comment]
> Rethink about it, I think putting .collectList in PG UsersRepository::listReactive may be a more common fix.

Agreed. THis avoids leaking this everywhere.

My 2 cents is try to reproduce the bug into PGUsersRepositoryTest too.

That way we would limit coupling and ease testing possible alternative solutions...

**Review by Arsnael — APPROVED** [review]

**Review by vttranlina — APPROVED** [review]

**Review by hungphan227 — APPROVED** [review]

**Comment by quantranhong1999** [comment]
> My 2 cents is try to reproduce the bug into PGUsersRepositoryTest too.

I succeed in reproducing that indeed.

**Comment by chibenwa** [comment]
If I put, say, 5 users, do I actually encounter the bug?

**Comment by quantranhong1999** [comment]
> If I put, say, 5 users, do I actually encounter the bug?

It does not happen with a small amount of users. 
BTW likely this is not paging related bug as we are not using it.  
`One common way to implement pagination in SQL is to use the LIMIT and OFFSET clauses in a SELECT statement.`

**Comment by chibenwa** [comment]
No I did not meant paging as in a UI

I meant paging as in a SQL driver. For instance Cassandra driver fetch a first page of 5000 items then when necessary to provide you some more results it fetches some more.

**Pull request merged**
