### PR TITLE
[PGSQL] Merge master branch to postgresql

### PR DESCRIPTION
**Pull request by vttranlina**

### CODE REVIEW

**Comment by chibenwa** [comment]
Don't hesitate to force push, not sure you can do a merge request here...

**Comment by Arsnael** [comment]
Github seems to say there is still conflicts?

**Comment by vttranlina** [comment]
> Don't hesitate to force push, not sure you can do a merge request here...

> Github seems to say there is still conflicts?


It looks better if the force push to `origin/postgresql`
I haven't permission to force push, -> I will close it

**Comment by Arsnael** [comment]
Force push are dangerous.... what about a PR with a rebase on origin/master?

**Pull request closed without merging**
