### PR TITLE
JAMES-3705 Refactoring POP3 handlers to be more extensible

### PR DESCRIPTION
**Pull request by ottoka**
A minor refactoring to make the POP3 RETR/TOP handlers more easily extensible: Retrieve the message content via a separate protected method.

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]
Overall OK.

The intent expressed in the ticket (quote `With this developers can more easily create custom variants of this command, to  access the session and message metadata, wrap the message stream to e.g. gather transfer statistics and monitor ultimate success/failure.`) sounds very legitimate to me and *might* even make it in the upstream project, depending how those are collected.

IMO if you are collecting those with the `MetricFactory` I would strongly encourage also contributing this to Apache James.

**Comment by ottoka** [comment]
Commented in the Jira ticket:

"My original intent was extensibility with minimal code change, hence just the lonely protected method. It still makes sense for this purpose, e.g. we hook up a custom monitoring solution that probably nobody else would be interested in.

I agree that it also makes sense to improve James metrics for POP3. I can take a look at integrating MetricFactory, but this is a different scope and a bigger change. I would prefer to do this in a separate ticket."

And a separate PR of course.

**Comment by chibenwa** [comment]
@ottoka : I let you this one for your first merge, as a test for you 2FA github setup ;-)

**Comment by ottoka** [comment]
Thanks, but it seems I still do not have the proper access rights. The only buttons I see here are "Comment" and "Close" (which I now know is something different). And the box at the bottom says "Only those with write access to this repository can merge pull requests." :-(

**Comment by chibenwa** [comment]
Well don't hesitate to ask if you want us to merge this on your behalf...

**Comment by chibenwa** [comment]
I did found this link, that **might** be usefull!

https://cwiki.apache.org/confluence/display/OPENWHISK/Accessing+Apache+GitHub+as+a+Committer

Here are the steps

 - Verify you have a Github ID enabled with 2FA https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/
 - Enter your Github ID into your Apache ID profile https://id.apache.org/
 - Merge your Apache and GitHub accounts using GitBox (Apache Account Linking utility): https://gitbox.apache.org/setup/ You should see 3 green checks in GitBox

Wait at least 30  minutes for an email inviting you to Apache GitHub Organization and accept invitation

 - After accepting the Github Invitation verify that you are a member of the team https://github.com/orgs/apache/teams/james-committers

**Comment by Arsnael** [comment]
Yes agreed. I remember before doing those steps I could merge but only from the command line. After doing this, could merge directly from the github interface. You should follow this procedure @ottoka :)

**Comment by chibenwa** [comment]
BTW I added this procedure (amongst others) in the Apache James guidelines! https://github.com/apache/james-project/pull/856

**Comment by ottoka** [comment]
Aha, I was missing the third step about gitbox! After doing that I was added to the james team about 30 mins later, and now I finally see a "Merge pull request" button. Thanks for digging up the step-by-step list!

**Comment by ottoka** [comment]
Seems it worked. By default the button seems to create a merge commit, but there are also "squash" and "rebase" options. Which one do you prefer?

**Comment by chibenwa** [comment]
> Seems it worked. By default the button seems to create a merge commit, but there are also "squash" and "rebase" options. Which one do you prefer?

Whatever as long as a clean history is produced.

-> If there is a single commit, or a bunch of commits that deserve to be one commit I prefer squash

-> If a complex and clean history was produced then I rebase to preserve it: the author likely put greate efforts on it. Merge would also achieve that goal.

-> A complex not clean history, I would ask the author to rebase himself...

> Seems it worked. By default the button seems to create a merge commit, but there are also "squash" and "rebase" options. Which one do you prefer?

Koodo!

The project documentation definitly lacks some committer docs - I often end up looking for ASF procedure links for long period of time. Hopefully https://github.com/apache/james-project/pull/856 will change that. If you see other things to include in it...

**Pull request merged**
