### PR TITLE
[WIP][REFACTOR] moves data-api configuration files to test sources

### PR DESCRIPTION
**Pull request by jeantil**
By being in the main sources, they were automatically available on the
classpath, potentially masking missing files and applying incorrect or
involuntary default configuration.

### CODE REVIEW

**Comment by jeantil** [comment]
I pushed this as wip to let the CI check for possible impacts, it's pretty high up in the module tree and checking it locally would block my laptop for quite a while ...
We discovered this as part of our work on scaling-puslar-smtp

**Review by chibenwa — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Comment by jeantil** [comment]
test this please

**Comment by chibenwa** [comment]
> test this please

Not sure this works. INFRA had issues. We might need to reopen this PR for Jenkins to take it into account...

https://ci-builds.apache.org/job/james/job/ApacheJames/view/change-requests/job/PR-1063

=> 404

**Comment by jeantil** [comment]
closing and reopening to get ci support

**Comment by jeantil** [comment]
superseded by https://github.com/apache/james-project/pull/1065

**Pull request closed without merging**
