### PR TITLE
[PGSQL] Update R2DBC + JOOQ driver

### PR DESCRIPTION
**Pull request by quantranhong1999**
Hopefully, we can remove the `.collectList() + flatMapIterables` workaround.

Let's see the build.

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]
GREAT WORK!

@quantranhong1999 do you confirm big paging requests were covered by unit tests?

**Comment by quantranhong1999** [comment]
> @quantranhong1999 do you confirm big paging requests were covered by unit tests?

We should have: https://github.com/apache/james-project/commit/78bd3374f355a474f809c14ec626f9f5d89ae4fc

**Comment by Arsnael** [comment]
Related or not? https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2462/1/

**Comment by quantranhong1999** [comment]
> Related or not? https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-2462/1/

It seems related. Let me check.

**Comment by quantranhong1999** [comment]
Sadly the reactor issue still persists with the new driver version.

**Review by hungphan227 — APPROVED** [review]

**Review by vttranlina — APPROVED** [review]

**Pull request merged**
