### PR TITLE
JAMES-3544 Add getUploadMetadata method for UploadRepository + add to UploadResolver

### PR DESCRIPTION
**Pull request by vttranlina**

### CODE REVIEW

**Comment by chibenwa** [comment]
IMO not needed.

Why do you want to work specifically with uploads?
Why not other blobs?
Isn't BlobResolver doing the job?

**Comment by vttranlina** [comment]
I just want to fetch only blob metadata (blobId, contentType, size), No need `content`

**Comment by chibenwa** [comment]
If truely needed (which I doubt) I believe we could rather have a metadata description as part of the BlobResolver?

**Comment by vttranlina** [comment]
You are right, Should be better when use `BlobResolvers`, than use only one UploadResolver

**Pull request closed without merging**
