### PR TITLE
[DUPLICATED] JAMES-3924 RabbitMQ mail queue updates: not performed

### PR DESCRIPTION
**Pull request by quantranhong1999**
Goal: help https://github.com/apache/james-project/pull/1623 moves on (no branch push permission).

### CODE REVIEW

**Comment by Arsnael** [comment]
Not sure tagging a test that was stable before as unstable just to pass the CI is alright..?

**Comment by quantranhong1999** [comment]
> Not sure tagging a test that was stable before as unstable just to pass the CI is alright..?

Those tests are just introduced therefore no stable before at all. And reason why I mark as Unstable explained here:
https://github.com/apache/james-project/pull/1623#discussion_r1278857168

**Review by Arsnael — APPROVED** [review]

**Review by vttranlina — APPROVED** [review]

**Comment by Arsnael** [comment]
Alright can we squash here? :)

**Review by chibenwa — APPROVED** [review]

**Comment by Arsnael** [comment]
Most of the builds are failing on cassandra startup container... but also all builds seem to end up on the same worker (builds45). I would bet there is maybe an issue on the worker side? I will duplicate this PR to force an other build in parallel on an other worker to see

**Pull request merged**
